from typing import Literal

MAV_AVSS_COMMAND_FAILURE_REASON = {
    1: "NOT_STEADY", "NOT_STEADY": 1,
    2: "DTM_NOT_ARMED", "DTM_NOT_ARMED": 2,
    3: "OTM_NOT_ARMED", "OTM_NOT_ARMED": 3
}
MavAvssCommandFailureReason = Literal["NOT_STEADY", "DTM_NOT_ARMED", "OTM_NOT_ARMED"]

AVSS_M300_OPERATION_MODE = {
    0: "MANUAL_CTRL", "MANUAL_CTRL": 0,
    1: "ATTITUDE", "ATTITUDE": 1,
    6: "P_GPS", "P_GPS": 6,
    9: "HOTPOINT_MODE", "HOTPOINT_MODE": 9,
    10: "ASSISTED_TAKEOFF", "ASSISTED_TAKEOFF": 10,
    11: "AUTO_TAKEOFF", "AUTO_TAKEOFF": 11,
    12: "AUTO_LANDING", "AUTO_LANDING": 12,
    15: "NAVI_GO_HOME", "NAVI_GO_HOME": 15,
    17: "NAVI_SDK_CTRL", "NAVI_SDK_CTRL": 17,
    31: "S_SPORT", "S_SPORT": 31,
    33: "FORCE_AUTO_LANDING", "FORCE_AUTO_LANDING": 33,
    38: "T_TRIPOD", "T_TRIPOD": 38,
    40: "SEARCH_MODE", "SEARCH_MODE": 40,
    41: "ENGINE_START", "ENGINE_START": 41
}
AvssM300OperationMode = Literal[
    "MANUAL_CTRL", "ATTITUDE", "P_GPS", "HOTPOINT_MODE", "ASSISTED_TAKEOFF", "AUTO_TAKEOFF", "AUTO_LANDING", "NAVI_GO_HOME", "NAVI_SDK_CTRL", "S_SPORT", "FORCE_AUTO_LANDING", "T_TRIPOD", "SEARCH_MODE", "ENGINE_START"]

AVSS_HORSEFLY_OPERATION_MODE = {
    0: "MANUAL_CTRL", "MANUAL_CTRL": 0,
    1: "AUTO_TAKEOFF", "AUTO_TAKEOFF": 1,
    2: "AUTO_LANDING", "AUTO_LANDING": 2,
    3: "NAVI_GO_HOME", "NAVI_GO_HOME": 3,
    4: "DROP", "DROP": 4
}
AvssHorseflyOperationMode = Literal["MANUAL_CTRL", "AUTO_TAKEOFF", "AUTO_LANDING", "NAVI_GO_HOME", "DROP"]
