from typing import Literal

HL_FAILURE_FLAG = {
    1: "GPS", "GPS": 1,
    2: "DIFFERENTIAL_PRESSURE", "DIFFERENTIAL_PRESSURE": 2,
    4: "ABSOLUTE_PRESSURE", "ABSOLUTE_PRESSURE": 4,
    8: "3D_ACCEL", "3D_ACCEL": 8,
    16: "3D_GYRO", "3D_GYRO": 16,
    32: "3D_MAG", "3D_MAG": 32,
    64: "TERRAIN", "TERRAIN": 64,
    128: "BATTERY", "BATTERY": 128,
    256: "RC_RECEIVER", "RC_RECEIVER": 256,
    512: "OFFBOARD_LINK", "OFFBOARD_LINK": 512,
    1024: "ENGINE", "ENGINE": 1024,
    2048: "GEOFENCE", "GEOFENCE": 2048,
    4096: "ESTIMATOR", "ESTIMATOR": 4096,
    8192: "MISSION", "MISSION": 8192
}
HlFailureFlag = Literal[
    "GPS", "DIFFERENTIAL_PRESSURE", "ABSOLUTE_PRESSURE", "3D_ACCEL", "3D_GYRO", "3D_MAG", "TERRAIN", "BATTERY", "RC_RECEIVER", "OFFBOARD_LINK", "ENGINE", "GEOFENCE", "ESTIMATOR", "MISSION"]

MAV_GOTO = {
    0: "DO_HOLD", "DO_HOLD": 0,
    1: "DO_CONTINUE", "DO_CONTINUE": 1,
    2: "HOLD_AT_CURRENT_POSITION", "HOLD_AT_CURRENT_POSITION": 2,
    3: "HOLD_AT_SPECIFIED_POSITION", "HOLD_AT_SPECIFIED_POSITION": 3
}
MavGoto = Literal["DO_HOLD", "DO_CONTINUE", "HOLD_AT_CURRENT_POSITION", "HOLD_AT_SPECIFIED_POSITION"]

MAV_MODE = {
    0: "PREFLIGHT", "PREFLIGHT": 0,
    64: "MANUAL_DISARMED", "MANUAL_DISARMED": 64,
    66: "TEST_DISARMED", "TEST_DISARMED": 66,
    80: "STABILIZE_DISARMED", "STABILIZE_DISARMED": 80,
    88: "GUIDED_DISARMED", "GUIDED_DISARMED": 88,
    92: "AUTO_DISARMED", "AUTO_DISARMED": 92,
    192: "MANUAL_ARMED", "MANUAL_ARMED": 192,
    194: "TEST_ARMED", "TEST_ARMED": 194,
    208: "STABILIZE_ARMED", "STABILIZE_ARMED": 208,
    216: "GUIDED_ARMED", "GUIDED_ARMED": 216,
    220: "AUTO_ARMED", "AUTO_ARMED": 220
}
MavMode = Literal[
    "PREFLIGHT", "MANUAL_DISARMED", "TEST_DISARMED", "STABILIZE_DISARMED", "GUIDED_DISARMED", "AUTO_DISARMED", "MANUAL_ARMED", "TEST_ARMED", "STABILIZE_ARMED", "GUIDED_ARMED", "AUTO_ARMED"]

MAV_SYS_STATUS_SENSOR = {
    1: "SENSOR_3D_GYRO", "SENSOR_3D_GYRO": 1,
    2: "SENSOR_3D_ACCEL", "SENSOR_3D_ACCEL": 2,
    4: "SENSOR_3D_MAG", "SENSOR_3D_MAG": 4,
    8: "SENSOR_ABSOLUTE_PRESSURE", "SENSOR_ABSOLUTE_PRESSURE": 8,
    16: "SENSOR_DIFFERENTIAL_PRESSURE", "SENSOR_DIFFERENTIAL_PRESSURE": 16,
    32: "SENSOR_GPS", "SENSOR_GPS": 32,
    64: "SENSOR_OPTICAL_FLOW", "SENSOR_OPTICAL_FLOW": 64,
    128: "SENSOR_VISION_POSITION", "SENSOR_VISION_POSITION": 128,
    256: "SENSOR_LASER_POSITION", "SENSOR_LASER_POSITION": 256,
    512: "SENSOR_EXTERNAL_GROUND_TRUTH", "SENSOR_EXTERNAL_GROUND_TRUTH": 512,
    1024: "SENSOR_ANGULAR_RATE_CONTROL", "SENSOR_ANGULAR_RATE_CONTROL": 1024,
    2048: "SENSOR_ATTITUDE_STABILIZATION", "SENSOR_ATTITUDE_STABILIZATION": 2048,
    4096: "SENSOR_YAW_POSITION", "SENSOR_YAW_POSITION": 4096,
    8192: "SENSOR_Z_ALTITUDE_CONTROL", "SENSOR_Z_ALTITUDE_CONTROL": 8192,
    16384: "SENSOR_XY_POSITION_CONTROL", "SENSOR_XY_POSITION_CONTROL": 16384,
    32768: "SENSOR_MOTOR_OUTPUTS", "SENSOR_MOTOR_OUTPUTS": 32768,
    65536: "SENSOR_RC_RECEIVER", "SENSOR_RC_RECEIVER": 65536,
    131072: "SENSOR_3D_GYRO2", "SENSOR_3D_GYRO2": 131072,
    262144: "SENSOR_3D_ACCEL2", "SENSOR_3D_ACCEL2": 262144,
    524288: "SENSOR_3D_MAG2", "SENSOR_3D_MAG2": 524288,
    1048576: "GEOFENCE", "GEOFENCE": 1048576,
    2097152: "AHRS", "AHRS": 2097152,
    4194304: "TERRAIN", "TERRAIN": 4194304,
    8388608: "REVERSE_MOTOR", "REVERSE_MOTOR": 8388608,
    16777216: "LOGGING", "LOGGING": 16777216,
    33554432: "SENSOR_BATTERY", "SENSOR_BATTERY": 33554432,
    67108864: "SENSOR_PROXIMITY", "SENSOR_PROXIMITY": 67108864,
    134217728: "SENSOR_SATCOM", "SENSOR_SATCOM": 134217728,
    268435456: "PREARM_CHECK", "PREARM_CHECK": 268435456,
    536870912: "OBSTACLE_AVOIDANCE", "OBSTACLE_AVOIDANCE": 536870912,
    1073741824: "SENSOR_PROPULSION", "SENSOR_PROPULSION": 1073741824,
    2147483648: "EXTENSION_USED", "EXTENSION_USED": 2147483648
}
MavSysStatusSensor = Literal[
    "SENSOR_3D_GYRO", "SENSOR_3D_ACCEL", "SENSOR_3D_MAG", "SENSOR_ABSOLUTE_PRESSURE", "SENSOR_DIFFERENTIAL_PRESSURE", "SENSOR_GPS", "SENSOR_OPTICAL_FLOW", "SENSOR_VISION_POSITION", "SENSOR_LASER_POSITION", "SENSOR_EXTERNAL_GROUND_TRUTH", "SENSOR_ANGULAR_RATE_CONTROL", "SENSOR_ATTITUDE_STABILIZATION", "SENSOR_YAW_POSITION", "SENSOR_Z_ALTITUDE_CONTROL", "SENSOR_XY_POSITION_CONTROL", "SENSOR_MOTOR_OUTPUTS", "SENSOR_RC_RECEIVER", "SENSOR_3D_GYRO2", "SENSOR_3D_ACCEL2", "SENSOR_3D_MAG2", "GEOFENCE", "AHRS", "TERRAIN", "REVERSE_MOTOR", "LOGGING", "SENSOR_BATTERY", "SENSOR_PROXIMITY", "SENSOR_SATCOM", "PREARM_CHECK", "OBSTACLE_AVOIDANCE", "SENSOR_PROPULSION", "EXTENSION_USED"]

MAV_SYS_STATUS_SENSOR_EXTENDED = {
    1: "RECOVERY_SYSTEM", "RECOVERY_SYSTEM": 1
}
MavSysStatusSensorExtended = Literal["RECOVERY_SYSTEM"]

MAV_FRAME = {
    0: "GLOBAL", "GLOBAL": 0,
    1: "LOCAL_NED", "LOCAL_NED": 1,
    2: "MISSION", "MISSION": 2,
    3: "GLOBAL_RELATIVE_ALT", "GLOBAL_RELATIVE_ALT": 3,
    4: "LOCAL_ENU", "LOCAL_ENU": 4,
    5: "GLOBAL_INT", "GLOBAL_INT": 5,
    6: "GLOBAL_RELATIVE_ALT_INT", "GLOBAL_RELATIVE_ALT_INT": 6,
    7: "LOCAL_OFFSET_NED", "LOCAL_OFFSET_NED": 7,
    8: "BODY_NED", "BODY_NED": 8,
    9: "BODY_OFFSET_NED", "BODY_OFFSET_NED": 9,
    10: "GLOBAL_TERRAIN_ALT", "GLOBAL_TERRAIN_ALT": 10,
    11: "GLOBAL_TERRAIN_ALT_INT", "GLOBAL_TERRAIN_ALT_INT": 11,
    12: "BODY_FRD", "BODY_FRD": 12,
    13: "RESERVED_13", "RESERVED_13": 13,
    14: "RESERVED_14", "RESERVED_14": 14,
    15: "RESERVED_15", "RESERVED_15": 15,
    16: "RESERVED_16", "RESERVED_16": 16,
    17: "RESERVED_17", "RESERVED_17": 17,
    18: "RESERVED_18", "RESERVED_18": 18,
    19: "RESERVED_19", "RESERVED_19": 19,
    20: "LOCAL_FRD", "LOCAL_FRD": 20,
    21: "LOCAL_FLU", "LOCAL_FLU": 21
}
MavFrame = Literal[
    "GLOBAL", "LOCAL_NED", "MISSION", "GLOBAL_RELATIVE_ALT", "LOCAL_ENU", "GLOBAL_INT", "GLOBAL_RELATIVE_ALT_INT", "LOCAL_OFFSET_NED", "BODY_NED", "BODY_OFFSET_NED", "GLOBAL_TERRAIN_ALT", "GLOBAL_TERRAIN_ALT_INT", "BODY_FRD", "RESERVED_13", "RESERVED_14", "RESERVED_15", "RESERVED_16", "RESERVED_17", "RESERVED_18", "RESERVED_19", "LOCAL_FRD", "LOCAL_FLU"]

MAVLINK_DATA_STREAM_TYPE = {
    0: "JPEG", "JPEG": 0,
    1: "BMP", "BMP": 1,
    2: "RAW8U", "RAW8U": 2,
    3: "RAW32U", "RAW32U": 3,
    4: "PGM", "PGM": 4,
    5: "PNG", "PNG": 5
}
MavlinkDataStreamType = Literal["JPEG", "BMP", "RAW8U", "RAW32U", "PGM", "PNG"]

FENCE_BREACH = {
    0: "NONE", "NONE": 0,
    1: "MINALT", "MINALT": 1,
    2: "MAXALT", "MAXALT": 2,
    3: "BOUNDARY", "BOUNDARY": 3
}
FenceBreach = Literal["NONE", "MINALT", "MAXALT", "BOUNDARY"]

FENCE_MITIGATE = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "NONE", "NONE": 1,
    2: "VEL_LIMIT", "VEL_LIMIT": 2
}
FenceMitigate = Literal["UNKNOWN", "NONE", "VEL_LIMIT"]

FENCE_TYPE = {
    1: "ALT_MAX", "ALT_MAX": 1,
    2: "CIRCLE", "CIRCLE": 2,
    4: "POLYGON", "POLYGON": 4,
    8: "ALT_MIN", "ALT_MIN": 8
}
FenceType = Literal["ALT_MAX", "CIRCLE", "POLYGON", "ALT_MIN"]

MAV_MOUNT_MODE = {
    0: "RETRACT", "RETRACT": 0,
    1: "NEUTRAL", "NEUTRAL": 1,
    2: "MAVLINK_TARGETING", "MAVLINK_TARGETING": 2,
    3: "RC_TARGETING", "RC_TARGETING": 3,
    4: "GPS_POINT", "GPS_POINT": 4,
    5: "SYSID_TARGET", "SYSID_TARGET": 5,
    6: "HOME_LOCATION", "HOME_LOCATION": 6
}
MavMountMode = Literal[
    "RETRACT", "NEUTRAL", "MAVLINK_TARGETING", "RC_TARGETING", "GPS_POINT", "SYSID_TARGET", "HOME_LOCATION"]

GIMBAL_DEVICE_CAP_FLAGS = {
    1: "HAS_RETRACT", "HAS_RETRACT": 1,
    2: "HAS_NEUTRAL", "HAS_NEUTRAL": 2,
    4: "HAS_ROLL_AXIS", "HAS_ROLL_AXIS": 4,
    8: "HAS_ROLL_FOLLOW", "HAS_ROLL_FOLLOW": 8,
    16: "HAS_ROLL_LOCK", "HAS_ROLL_LOCK": 16,
    32: "HAS_PITCH_AXIS", "HAS_PITCH_AXIS": 32,
    64: "HAS_PITCH_FOLLOW", "HAS_PITCH_FOLLOW": 64,
    128: "HAS_PITCH_LOCK", "HAS_PITCH_LOCK": 128,
    256: "HAS_YAW_AXIS", "HAS_YAW_AXIS": 256,
    512: "HAS_YAW_FOLLOW", "HAS_YAW_FOLLOW": 512,
    1024: "HAS_YAW_LOCK", "HAS_YAW_LOCK": 1024,
    2048: "SUPPORTS_INFINITE_YAW", "SUPPORTS_INFINITE_YAW": 2048,
    4096: "SUPPORTS_YAW_IN_EARTH_FRAME", "SUPPORTS_YAW_IN_EARTH_FRAME": 4096,
    8192: "HAS_RC_INPUTS", "HAS_RC_INPUTS": 8192
}
GimbalDeviceCapFlags = Literal[
    "HAS_RETRACT", "HAS_NEUTRAL", "HAS_ROLL_AXIS", "HAS_ROLL_FOLLOW", "HAS_ROLL_LOCK", "HAS_PITCH_AXIS", "HAS_PITCH_FOLLOW", "HAS_PITCH_LOCK", "HAS_YAW_AXIS", "HAS_YAW_FOLLOW", "HAS_YAW_LOCK", "SUPPORTS_INFINITE_YAW", "SUPPORTS_YAW_IN_EARTH_FRAME", "HAS_RC_INPUTS"]

GIMBAL_MANAGER_CAP_FLAGS = {
    1: "HAS_RETRACT", "HAS_RETRACT": 1,
    2: "HAS_NEUTRAL", "HAS_NEUTRAL": 2,
    4: "HAS_ROLL_AXIS", "HAS_ROLL_AXIS": 4,
    8: "HAS_ROLL_FOLLOW", "HAS_ROLL_FOLLOW": 8,
    16: "HAS_ROLL_LOCK", "HAS_ROLL_LOCK": 16,
    32: "HAS_PITCH_AXIS", "HAS_PITCH_AXIS": 32,
    64: "HAS_PITCH_FOLLOW", "HAS_PITCH_FOLLOW": 64,
    128: "HAS_PITCH_LOCK", "HAS_PITCH_LOCK": 128,
    256: "HAS_YAW_AXIS", "HAS_YAW_AXIS": 256,
    512: "HAS_YAW_FOLLOW", "HAS_YAW_FOLLOW": 512,
    1024: "HAS_YAW_LOCK", "HAS_YAW_LOCK": 1024,
    2048: "SUPPORTS_INFINITE_YAW", "SUPPORTS_INFINITE_YAW": 2048,
    4096: "SUPPORTS_YAW_IN_EARTH_FRAME", "SUPPORTS_YAW_IN_EARTH_FRAME": 4096,
    8192: "HAS_RC_INPUTS", "HAS_RC_INPUTS": 8192,
    65536: "CAN_POINT_LOCATION_LOCAL", "CAN_POINT_LOCATION_LOCAL": 65536,
    131072: "CAN_POINT_LOCATION_GLOBAL", "CAN_POINT_LOCATION_GLOBAL": 131072
}
GimbalManagerCapFlags = Literal[
    "HAS_RETRACT", "HAS_NEUTRAL", "HAS_ROLL_AXIS", "HAS_ROLL_FOLLOW", "HAS_ROLL_LOCK", "HAS_PITCH_AXIS", "HAS_PITCH_FOLLOW", "HAS_PITCH_LOCK", "HAS_YAW_AXIS", "HAS_YAW_FOLLOW", "HAS_YAW_LOCK", "SUPPORTS_INFINITE_YAW", "SUPPORTS_YAW_IN_EARTH_FRAME", "HAS_RC_INPUTS", "CAN_POINT_LOCATION_LOCAL", "CAN_POINT_LOCATION_GLOBAL"]

GIMBAL_DEVICE_FLAGS = {
    1: "RETRACT", "RETRACT": 1,
    2: "NEUTRAL", "NEUTRAL": 2,
    4: "ROLL_LOCK", "ROLL_LOCK": 4,
    8: "PITCH_LOCK", "PITCH_LOCK": 8,
    16: "YAW_LOCK", "YAW_LOCK": 16,
    32: "YAW_IN_VEHICLE_FRAME", "YAW_IN_VEHICLE_FRAME": 32,
    64: "YAW_IN_EARTH_FRAME", "YAW_IN_EARTH_FRAME": 64,
    128: "ACCEPTS_YAW_IN_EARTH_FRAME", "ACCEPTS_YAW_IN_EARTH_FRAME": 128,
    256: "RC_EXCLUSIVE", "RC_EXCLUSIVE": 256,
    512: "RC_MIXED", "RC_MIXED": 512
}
GimbalDeviceFlags = Literal[
    "RETRACT", "NEUTRAL", "ROLL_LOCK", "PITCH_LOCK", "YAW_LOCK", "YAW_IN_VEHICLE_FRAME", "YAW_IN_EARTH_FRAME", "ACCEPTS_YAW_IN_EARTH_FRAME", "RC_EXCLUSIVE", "RC_MIXED"]

GIMBAL_MANAGER_FLAGS = {
    1: "RETRACT", "RETRACT": 1,
    2: "NEUTRAL", "NEUTRAL": 2,
    4: "ROLL_LOCK", "ROLL_LOCK": 4,
    8: "PITCH_LOCK", "PITCH_LOCK": 8,
    16: "YAW_LOCK", "YAW_LOCK": 16,
    32: "YAW_IN_VEHICLE_FRAME", "YAW_IN_VEHICLE_FRAME": 32,
    64: "YAW_IN_EARTH_FRAME", "YAW_IN_EARTH_FRAME": 64,
    128: "ACCEPTS_YAW_IN_EARTH_FRAME", "ACCEPTS_YAW_IN_EARTH_FRAME": 128,
    256: "RC_EXCLUSIVE", "RC_EXCLUSIVE": 256,
    512: "RC_MIXED", "RC_MIXED": 512
}
GimbalManagerFlags = Literal[
    "RETRACT", "NEUTRAL", "ROLL_LOCK", "PITCH_LOCK", "YAW_LOCK", "YAW_IN_VEHICLE_FRAME", "YAW_IN_EARTH_FRAME", "ACCEPTS_YAW_IN_EARTH_FRAME", "RC_EXCLUSIVE", "RC_MIXED"]

GIMBAL_DEVICE_ERROR_FLAGS = {
    1: "AT_ROLL_LIMIT", "AT_ROLL_LIMIT": 1,
    2: "AT_PITCH_LIMIT", "AT_PITCH_LIMIT": 2,
    4: "AT_YAW_LIMIT", "AT_YAW_LIMIT": 4,
    8: "ENCODER_ERROR", "ENCODER_ERROR": 8,
    16: "POWER_ERROR", "POWER_ERROR": 16,
    32: "MOTOR_ERROR", "MOTOR_ERROR": 32,
    64: "SOFTWARE_ERROR", "SOFTWARE_ERROR": 64,
    128: "COMMS_ERROR", "COMMS_ERROR": 128,
    256: "CALIBRATION_RUNNING", "CALIBRATION_RUNNING": 256,
    512: "NO_MANAGER", "NO_MANAGER": 512
}
GimbalDeviceErrorFlags = Literal[
    "AT_ROLL_LIMIT", "AT_PITCH_LIMIT", "AT_YAW_LIMIT", "ENCODER_ERROR", "POWER_ERROR", "MOTOR_ERROR", "SOFTWARE_ERROR", "COMMS_ERROR", "CALIBRATION_RUNNING", "NO_MANAGER"]

GRIPPER_ACTIONS = {
    0: "RELEASE", "RELEASE": 0,
    1: "GRAB", "GRAB": 1
}
GripperActions = Literal["RELEASE", "GRAB"]

WINCH_ACTIONS = {
    0: "RELAXED", "RELAXED": 0,
    1: "RELATIVE_LENGTH_CONTROL", "RELATIVE_LENGTH_CONTROL": 1,
    2: "RATE_CONTROL", "RATE_CONTROL": 2,
    3: "LOCK", "LOCK": 3,
    4: "DELIVER", "DELIVER": 4,
    5: "HOLD", "HOLD": 5,
    6: "RETRACT", "RETRACT": 6,
    7: "LOAD_LINE", "LOAD_LINE": 7,
    8: "ABANDON_LINE", "ABANDON_LINE": 8,
    9: "LOAD_PAYLOAD", "LOAD_PAYLOAD": 9
}
WinchActions = Literal[
    "RELAXED", "RELATIVE_LENGTH_CONTROL", "RATE_CONTROL", "LOCK", "DELIVER", "HOLD", "RETRACT", "LOAD_LINE", "ABANDON_LINE", "LOAD_PAYLOAD"]

UAVCAN_NODE_HEALTH = {
    0: "OK", "OK": 0,
    1: "WARNING", "WARNING": 1,
    2: "ERROR", "ERROR": 2,
    3: "CRITICAL", "CRITICAL": 3
}
UavcanNodeHealth = Literal["OK", "WARNING", "ERROR", "CRITICAL"]

UAVCAN_NODE_MODE = {
    0: "OPERATIONAL", "OPERATIONAL": 0,
    1: "INITIALIZATION", "INITIALIZATION": 1,
    2: "MAINTENANCE", "MAINTENANCE": 2,
    3: "SOFTWARE_UPDATE", "SOFTWARE_UPDATE": 3,
    7: "OFFLINE", "OFFLINE": 7
}
UavcanNodeMode = Literal["OPERATIONAL", "INITIALIZATION", "MAINTENANCE", "SOFTWARE_UPDATE", "OFFLINE"]

ESC_CONNECTION_TYPE = {
    0: "PPM", "PPM": 0,
    1: "SERIAL", "SERIAL": 1,
    2: "ONESHOT", "ONESHOT": 2,
    3: "I2C", "I2C": 3,
    4: "CAN", "CAN": 4,
    5: "DSHOT", "DSHOT": 5
}
EscConnectionType = Literal["PPM", "SERIAL", "ONESHOT", "I2C", "CAN", "DSHOT"]

ESC_FAILURE_FLAGS = {
    1: "OVER_CURRENT", "OVER_CURRENT": 1,
    2: "OVER_VOLTAGE", "OVER_VOLTAGE": 2,
    4: "OVER_TEMPERATURE", "OVER_TEMPERATURE": 4,
    8: "OVER_RPM", "OVER_RPM": 8,
    16: "INCONSISTENT_CMD", "INCONSISTENT_CMD": 16,
    32: "MOTOR_STUCK", "MOTOR_STUCK": 32,
    64: "GENERIC", "GENERIC": 64
}
EscFailureFlags = Literal[
    "OVER_CURRENT", "OVER_VOLTAGE", "OVER_TEMPERATURE", "OVER_RPM", "INCONSISTENT_CMD", "MOTOR_STUCK", "GENERIC"]

STORAGE_STATUS = {
    0: "EMPTY", "EMPTY": 0,
    1: "UNFORMATTED", "UNFORMATTED": 1,
    2: "READY", "READY": 2,
    3: "NOT_SUPPORTED", "NOT_SUPPORTED": 3
}
StorageStatus = Literal["EMPTY", "UNFORMATTED", "READY", "NOT_SUPPORTED"]

STORAGE_TYPE = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "USB_STICK", "USB_STICK": 1,
    2: "SD", "SD": 2,
    3: "MICROSD", "MICROSD": 3,
    4: "CF", "CF": 4,
    5: "CFE", "CFE": 5,
    6: "XQD", "XQD": 6,
    7: "HD", "HD": 7,
    254: "OTHER", "OTHER": 254
}
StorageType = Literal["UNKNOWN", "USB_STICK", "SD", "MICROSD", "CF", "CFE", "XQD", "HD", "OTHER"]

STORAGE_USAGE_FLAG = {
    1: "SET", "SET": 1,
    2: "PHOTO", "PHOTO": 2,
    4: "VIDEO", "VIDEO": 4,
    8: "LOGS", "LOGS": 8
}
StorageUsageFlag = Literal["SET", "PHOTO", "VIDEO", "LOGS"]

ORBIT_YAW_BEHAVIOUR = {
    0: "HOLD_FRONT_TO_CIRCLE_CENTER", "HOLD_FRONT_TO_CIRCLE_CENTER": 0,
    1: "HOLD_INITIAL_HEADING", "HOLD_INITIAL_HEADING": 1,
    2: "UNCONTROLLED", "UNCONTROLLED": 2,
    3: "HOLD_FRONT_TANGENT_TO_CIRCLE", "HOLD_FRONT_TANGENT_TO_CIRCLE": 3,
    4: "RC_CONTROLLED", "RC_CONTROLLED": 4,
    5: "UNCHANGED", "UNCHANGED": 5
}
OrbitYawBehaviour = Literal[
    "HOLD_FRONT_TO_CIRCLE_CENTER", "HOLD_INITIAL_HEADING", "UNCONTROLLED", "HOLD_FRONT_TANGENT_TO_CIRCLE", "RC_CONTROLLED", "UNCHANGED"]

WIFI_CONFIG_AP_RESPONSE = {
    0: "UNDEFINED", "UNDEFINED": 0,
    1: "ACCEPTED", "ACCEPTED": 1,
    2: "REJECTED", "REJECTED": 2,
    3: "MODE_ERROR", "MODE_ERROR": 3,
    4: "SSID_ERROR", "SSID_ERROR": 4,
    5: "PASSWORD_ERROR", "PASSWORD_ERROR": 5
}
WifiConfigApResponse = Literal["UNDEFINED", "ACCEPTED", "REJECTED", "MODE_ERROR", "SSID_ERROR", "PASSWORD_ERROR"]

CELLULAR_CONFIG_RESPONSE = {
    0: "RESPONSE_ACCEPTED", "RESPONSE_ACCEPTED": 0,
    1: "RESPONSE_APN_ERROR", "RESPONSE_APN_ERROR": 1,
    2: "RESPONSE_PIN_ERROR", "RESPONSE_PIN_ERROR": 2,
    3: "RESPONSE_REJECTED", "RESPONSE_REJECTED": 3,
    4: "BLOCKED_PUK_REQUIRED", "BLOCKED_PUK_REQUIRED": 4
}
CellularConfigResponse = Literal[
    "RESPONSE_ACCEPTED", "RESPONSE_APN_ERROR", "RESPONSE_PIN_ERROR", "RESPONSE_REJECTED", "BLOCKED_PUK_REQUIRED"]

WIFI_CONFIG_AP_MODE = {
    0: "UNDEFINED", "UNDEFINED": 0,
    1: "AP", "AP": 1,
    2: "STATION", "STATION": 2,
    3: "DISABLED", "DISABLED": 3
}
WifiConfigApMode = Literal["UNDEFINED", "AP", "STATION", "DISABLED"]

COMP_METADATA_TYPE = {
    0: "GENERAL", "GENERAL": 0,
    1: "PARAMETER", "PARAMETER": 1,
    2: "COMMANDS", "COMMANDS": 2,
    3: "PERIPHERALS", "PERIPHERALS": 3,
    4: "EVENTS", "EVENTS": 4,
    5: "ACTUATORS", "ACTUATORS": 5
}
CompMetadataType = Literal["GENERAL", "PARAMETER", "COMMANDS", "PERIPHERALS", "EVENTS", "ACTUATORS"]

ACTUATOR_CONFIGURATION = {
    0: "NONE", "NONE": 0,
    1: "BEEP", "BEEP": 1,
    2: "3D_MODE_ON", "3D_MODE_ON": 2,
    3: "3D_MODE_OFF", "3D_MODE_OFF": 3,
    4: "SPIN_DIRECTION1", "SPIN_DIRECTION1": 4,
    5: "SPIN_DIRECTION2", "SPIN_DIRECTION2": 5
}
ActuatorConfiguration = Literal["NONE", "BEEP", "3D_MODE_ON", "3D_MODE_OFF", "SPIN_DIRECTION1", "SPIN_DIRECTION2"]

ACTUATOR_OUTPUT_FUNCTION = {
    0: "NONE", "NONE": 0,
    1: "MOTOR1", "MOTOR1": 1,
    2: "MOTOR2", "MOTOR2": 2,
    3: "MOTOR3", "MOTOR3": 3,
    4: "MOTOR4", "MOTOR4": 4,
    5: "MOTOR5", "MOTOR5": 5,
    6: "MOTOR6", "MOTOR6": 6,
    7: "MOTOR7", "MOTOR7": 7,
    8: "MOTOR8", "MOTOR8": 8,
    9: "MOTOR9", "MOTOR9": 9,
    10: "MOTOR10", "MOTOR10": 10,
    11: "MOTOR11", "MOTOR11": 11,
    12: "MOTOR12", "MOTOR12": 12,
    13: "MOTOR13", "MOTOR13": 13,
    14: "MOTOR14", "MOTOR14": 14,
    15: "MOTOR15", "MOTOR15": 15,
    16: "MOTOR16", "MOTOR16": 16,
    33: "SERVO1", "SERVO1": 33,
    34: "SERVO2", "SERVO2": 34,
    35: "SERVO3", "SERVO3": 35,
    36: "SERVO4", "SERVO4": 36,
    37: "SERVO5", "SERVO5": 37,
    38: "SERVO6", "SERVO6": 38,
    39: "SERVO7", "SERVO7": 39,
    40: "SERVO8", "SERVO8": 40,
    41: "SERVO9", "SERVO9": 41,
    42: "SERVO10", "SERVO10": 42,
    43: "SERVO11", "SERVO11": 43,
    44: "SERVO12", "SERVO12": 44,
    45: "SERVO13", "SERVO13": 45,
    46: "SERVO14", "SERVO14": 46,
    47: "SERVO15", "SERVO15": 47,
    48: "SERVO16", "SERVO16": 48
}
ActuatorOutputFunction = Literal[
    "NONE", "MOTOR1", "MOTOR2", "MOTOR3", "MOTOR4", "MOTOR5", "MOTOR6", "MOTOR7", "MOTOR8", "MOTOR9", "MOTOR10", "MOTOR11", "MOTOR12", "MOTOR13", "MOTOR14", "MOTOR15", "MOTOR16", "SERVO1", "SERVO2", "SERVO3", "SERVO4", "SERVO5", "SERVO6", "SERVO7", "SERVO8", "SERVO9", "SERVO10", "SERVO11", "SERVO12", "SERVO13", "SERVO14", "SERVO15", "SERVO16"]

AUTOTUNE_AXIS = {
    1: "ROLL", "ROLL": 1,
    2: "PITCH", "PITCH": 2,
    4: "YAW", "YAW": 4
}
AutotuneAxis = Literal["ROLL", "PITCH", "YAW"]

PREFLIGHT_STORAGE_PARAMETER_ACTION = {
    0: "READ_PERSISTENT", "READ_PERSISTENT": 0,
    1: "WRITE_PERSISTENT", "WRITE_PERSISTENT": 1,
    2: "RESET_CONFIG_DEFAULT", "RESET_CONFIG_DEFAULT": 2,
    3: "RESET_SENSOR_DEFAULT", "RESET_SENSOR_DEFAULT": 3,
    4: "RESET_ALL_DEFAULT", "RESET_ALL_DEFAULT": 4
}
PreflightStorageParameterAction = Literal[
    "READ_PERSISTENT", "WRITE_PERSISTENT", "RESET_CONFIG_DEFAULT", "RESET_SENSOR_DEFAULT", "RESET_ALL_DEFAULT"]

PREFLIGHT_STORAGE_MISSION_ACTION = {
    0: "READ_PERSISTENT", "READ_PERSISTENT": 0,
    1: "WRITE_PERSISTENT", "WRITE_PERSISTENT": 1,
    2: "RESET_DEFAULT", "RESET_DEFAULT": 2
}
PreflightStorageMissionAction = Literal["READ_PERSISTENT", "WRITE_PERSISTENT", "RESET_DEFAULT"]

REBOOT_SHUTDOWN_ACTION = {
    0: "NONE", "NONE": 0,
    1: "REBOOT", "REBOOT": 1,
    2: "SHUTDOWN", "SHUTDOWN": 2,
    3: "REBOOT_TO_BOOTLOADER", "REBOOT_TO_BOOTLOADER": 3,
    4: "POWER_ON", "POWER_ON": 4
}
RebootShutdownAction = Literal["NONE", "REBOOT", "SHUTDOWN", "REBOOT_TO_BOOTLOADER", "POWER_ON"]

REBOOT_SHUTDOWN_CONDITIONS = {
    0: "SAFETY_INTERLOCKED", "SAFETY_INTERLOCKED": 0,
    20190226: "FORCE", "FORCE": 20190226
}
RebootShutdownConditions = Literal["SAFETY_INTERLOCKED", "FORCE"]

MAV_DATA_STREAM = {
    0: "ALL", "ALL": 0,
    1: "RAW_SENSORS", "RAW_SENSORS": 1,
    2: "EXTENDED_STATUS", "EXTENDED_STATUS": 2,
    3: "RC_CHANNELS", "RC_CHANNELS": 3,
    4: "RAW_CONTROLLER", "RAW_CONTROLLER": 4,
    6: "POSITION", "POSITION": 6,
    10: "EXTRA1", "EXTRA1": 10,
    11: "EXTRA2", "EXTRA2": 11,
    12: "EXTRA3", "EXTRA3": 12
}
MavDataStream = Literal[
    "ALL", "RAW_SENSORS", "EXTENDED_STATUS", "RC_CHANNELS", "RAW_CONTROLLER", "POSITION", "EXTRA1", "EXTRA2", "EXTRA3"]

MAV_ROI = {
    0: "NONE", "NONE": 0,
    1: "WPNEXT", "WPNEXT": 1,
    2: "WPINDEX", "WPINDEX": 2,
    3: "LOCATION", "LOCATION": 3,
    4: "TARGET", "TARGET": 4
}
MavRoi = Literal["NONE", "WPNEXT", "WPINDEX", "LOCATION", "TARGET"]

MAV_PARAM_TYPE = {
    1: "UINT8", "UINT8": 1,
    2: "INT8", "INT8": 2,
    3: "UINT16", "UINT16": 3,
    4: "INT16", "INT16": 4,
    5: "UINT32", "UINT32": 5,
    6: "INT32", "INT32": 6,
    7: "UINT64", "UINT64": 7,
    8: "INT64", "INT64": 8,
    9: "REAL32", "REAL32": 9,
    10: "REAL64", "REAL64": 10
}
MavParamType = Literal["UINT8", "INT8", "UINT16", "INT16", "UINT32", "INT32", "UINT64", "INT64", "REAL32", "REAL64"]

MAV_PARAM_EXT_TYPE = {
    1: "UINT8", "UINT8": 1,
    2: "INT8", "INT8": 2,
    3: "UINT16", "UINT16": 3,
    4: "INT16", "INT16": 4,
    5: "UINT32", "UINT32": 5,
    6: "INT32", "INT32": 6,
    7: "UINT64", "UINT64": 7,
    8: "INT64", "INT64": 8,
    9: "REAL32", "REAL32": 9,
    10: "REAL64", "REAL64": 10,
    11: "CUSTOM", "CUSTOM": 11
}
MavParamExtType = Literal[
    "UINT8", "INT8", "UINT16", "INT16", "UINT32", "INT32", "UINT64", "INT64", "REAL32", "REAL64", "CUSTOM"]

MAV_RESULT = {
    0: "ACCEPTED", "ACCEPTED": 0,
    1: "TEMPORARILY_REJECTED", "TEMPORARILY_REJECTED": 1,
    2: "DENIED", "DENIED": 2,
    3: "UNSUPPORTED", "UNSUPPORTED": 3,
    4: "FAILED", "FAILED": 4,
    5: "IN_PROGRESS", "IN_PROGRESS": 5,
    6: "CANCELLED", "CANCELLED": 6,
    7: "COMMAND_LONG_ONLY", "COMMAND_LONG_ONLY": 7,
    8: "COMMAND_INT_ONLY", "COMMAND_INT_ONLY": 8,
    9: "COMMAND_UNSUPPORTED_MAV_FRAME", "COMMAND_UNSUPPORTED_MAV_FRAME": 9
}
MavResult = Literal[
    "ACCEPTED", "TEMPORARILY_REJECTED", "DENIED", "UNSUPPORTED", "FAILED", "IN_PROGRESS", "CANCELLED", "COMMAND_LONG_ONLY", "COMMAND_INT_ONLY", "COMMAND_UNSUPPORTED_MAV_FRAME"]

MAV_MISSION_RESULT = {
    0: "ACCEPTED", "ACCEPTED": 0,
    1: "ERROR", "ERROR": 1,
    2: "UNSUPPORTED_FRAME", "UNSUPPORTED_FRAME": 2,
    3: "UNSUPPORTED", "UNSUPPORTED": 3,
    4: "NO_SPACE", "NO_SPACE": 4,
    5: "INVALID", "INVALID": 5,
    6: "INVALID_PARAM1", "INVALID_PARAM1": 6,
    7: "INVALID_PARAM2", "INVALID_PARAM2": 7,
    8: "INVALID_PARAM3", "INVALID_PARAM3": 8,
    9: "INVALID_PARAM4", "INVALID_PARAM4": 9,
    10: "INVALID_PARAM5_X", "INVALID_PARAM5_X": 10,
    11: "INVALID_PARAM6_Y", "INVALID_PARAM6_Y": 11,
    12: "INVALID_PARAM7", "INVALID_PARAM7": 12,
    13: "INVALID_SEQUENCE", "INVALID_SEQUENCE": 13,
    14: "DENIED", "DENIED": 14,
    15: "OPERATION_CANCELLED", "OPERATION_CANCELLED": 15
}
MavMissionResult = Literal[
    "ACCEPTED", "ERROR", "UNSUPPORTED_FRAME", "UNSUPPORTED", "NO_SPACE", "INVALID", "INVALID_PARAM1", "INVALID_PARAM2", "INVALID_PARAM3", "INVALID_PARAM4", "INVALID_PARAM5_X", "INVALID_PARAM6_Y", "INVALID_PARAM7", "INVALID_SEQUENCE", "DENIED", "OPERATION_CANCELLED"]

MAV_SEVERITY = {
    0: "EMERGENCY", "EMERGENCY": 0,
    1: "ALERT", "ALERT": 1,
    2: "CRITICAL", "CRITICAL": 2,
    3: "ERROR", "ERROR": 3,
    4: "WARNING", "WARNING": 4,
    5: "NOTICE", "NOTICE": 5,
    6: "INFO", "INFO": 6,
    7: "DEBUG", "DEBUG": 7
}
MavSeverity = Literal["EMERGENCY", "ALERT", "CRITICAL", "ERROR", "WARNING", "NOTICE", "INFO", "DEBUG"]

MAV_POWER_STATUS = {
    1: "BRICK_VALID", "BRICK_VALID": 1,
    2: "SERVO_VALID", "SERVO_VALID": 2,
    4: "USB_CONNECTED", "USB_CONNECTED": 4,
    8: "PERIPH_OVERCURRENT", "PERIPH_OVERCURRENT": 8,
    16: "PERIPH_HIPOWER_OVERCURRENT", "PERIPH_HIPOWER_OVERCURRENT": 16,
    32: "CHANGED", "CHANGED": 32
}
MavPowerStatus = Literal[
    "BRICK_VALID", "SERVO_VALID", "USB_CONNECTED", "PERIPH_OVERCURRENT", "PERIPH_HIPOWER_OVERCURRENT", "CHANGED"]

SERIAL_CONTROL_DEV = {
    0: "DEV_TELEM1", "DEV_TELEM1": 0,
    1: "DEV_TELEM2", "DEV_TELEM2": 1,
    2: "DEV_GPS1", "DEV_GPS1": 2,
    3: "DEV_GPS2", "DEV_GPS2": 3,
    10: "DEV_SHELL", "DEV_SHELL": 10,
    100: "SERIAL0", "SERIAL0": 100,
    101: "SERIAL1", "SERIAL1": 101,
    102: "SERIAL2", "SERIAL2": 102,
    103: "SERIAL3", "SERIAL3": 103,
    104: "SERIAL4", "SERIAL4": 104,
    105: "SERIAL5", "SERIAL5": 105,
    106: "SERIAL6", "SERIAL6": 106,
    107: "SERIAL7", "SERIAL7": 107,
    108: "SERIAL8", "SERIAL8": 108,
    109: "SERIAL9", "SERIAL9": 109
}
SerialControlDev = Literal[
    "DEV_TELEM1", "DEV_TELEM2", "DEV_GPS1", "DEV_GPS2", "DEV_SHELL", "SERIAL0", "SERIAL1", "SERIAL2", "SERIAL3", "SERIAL4", "SERIAL5", "SERIAL6", "SERIAL7", "SERIAL8", "SERIAL9"]

SERIAL_CONTROL_FLAG = {
    1: "REPLY", "REPLY": 1,
    2: "RESPOND", "RESPOND": 2,
    4: "EXCLUSIVE", "EXCLUSIVE": 4,
    8: "BLOCKING", "BLOCKING": 8,
    16: "MULTI", "MULTI": 16
}
SerialControlFlag = Literal["REPLY", "RESPOND", "EXCLUSIVE", "BLOCKING", "MULTI"]

MAV_DISTANCE_SENSOR = {
    0: "LASER", "LASER": 0,
    1: "ULTRASOUND", "ULTRASOUND": 1,
    2: "INFRARED", "INFRARED": 2,
    3: "RADAR", "RADAR": 3,
    4: "UNKNOWN", "UNKNOWN": 4
}
MavDistanceSensor = Literal["LASER", "ULTRASOUND", "INFRARED", "RADAR", "UNKNOWN"]

MAV_SENSOR_ORIENTATION = {
    0: "NONE", "NONE": 0,
    1: "YAW_45", "YAW_45": 1,
    2: "YAW_90", "YAW_90": 2,
    3: "YAW_135", "YAW_135": 3,
    4: "YAW_180", "YAW_180": 4,
    5: "YAW_225", "YAW_225": 5,
    6: "YAW_270", "YAW_270": 6,
    7: "YAW_315", "YAW_315": 7,
    8: "ROLL_180", "ROLL_180": 8,
    9: "ROLL_180_YAW_45", "ROLL_180_YAW_45": 9,
    10: "ROLL_180_YAW_90", "ROLL_180_YAW_90": 10,
    11: "ROLL_180_YAW_135", "ROLL_180_YAW_135": 11,
    12: "PITCH_180", "PITCH_180": 12,
    13: "ROLL_180_YAW_225", "ROLL_180_YAW_225": 13,
    14: "ROLL_180_YAW_270", "ROLL_180_YAW_270": 14,
    15: "ROLL_180_YAW_315", "ROLL_180_YAW_315": 15,
    16: "ROLL_90", "ROLL_90": 16,
    17: "ROLL_90_YAW_45", "ROLL_90_YAW_45": 17,
    18: "ROLL_90_YAW_90", "ROLL_90_YAW_90": 18,
    19: "ROLL_90_YAW_135", "ROLL_90_YAW_135": 19,
    20: "ROLL_270", "ROLL_270": 20,
    21: "ROLL_270_YAW_45", "ROLL_270_YAW_45": 21,
    22: "ROLL_270_YAW_90", "ROLL_270_YAW_90": 22,
    23: "ROLL_270_YAW_135", "ROLL_270_YAW_135": 23,
    24: "PITCH_90", "PITCH_90": 24,
    25: "PITCH_270", "PITCH_270": 25,
    26: "PITCH_180_YAW_90", "PITCH_180_YAW_90": 26,
    27: "PITCH_180_YAW_270", "PITCH_180_YAW_270": 27,
    28: "ROLL_90_PITCH_90", "ROLL_90_PITCH_90": 28,
    29: "ROLL_180_PITCH_90", "ROLL_180_PITCH_90": 29,
    30: "ROLL_270_PITCH_90", "ROLL_270_PITCH_90": 30,
    31: "ROLL_90_PITCH_180", "ROLL_90_PITCH_180": 31,
    32: "ROLL_270_PITCH_180", "ROLL_270_PITCH_180": 32,
    33: "ROLL_90_PITCH_270", "ROLL_90_PITCH_270": 33,
    34: "ROLL_180_PITCH_270", "ROLL_180_PITCH_270": 34,
    35: "ROLL_270_PITCH_270", "ROLL_270_PITCH_270": 35,
    36: "ROLL_90_PITCH_180_YAW_90", "ROLL_90_PITCH_180_YAW_90": 36,
    37: "ROLL_90_YAW_270", "ROLL_90_YAW_270": 37,
    38: "ROLL_90_PITCH_68_YAW_293", "ROLL_90_PITCH_68_YAW_293": 38,
    39: "PITCH_315", "PITCH_315": 39,
    40: "ROLL_90_PITCH_315", "ROLL_90_PITCH_315": 40,
    100: "CUSTOM", "CUSTOM": 100
}
MavSensorOrientation = Literal[
    "NONE", "YAW_45", "YAW_90", "YAW_135", "YAW_180", "YAW_225", "YAW_270", "YAW_315", "ROLL_180", "ROLL_180_YAW_45", "ROLL_180_YAW_90", "ROLL_180_YAW_135", "PITCH_180", "ROLL_180_YAW_225", "ROLL_180_YAW_270", "ROLL_180_YAW_315", "ROLL_90", "ROLL_90_YAW_45", "ROLL_90_YAW_90", "ROLL_90_YAW_135", "ROLL_270", "ROLL_270_YAW_45", "ROLL_270_YAW_90", "ROLL_270_YAW_135", "PITCH_90", "PITCH_270", "PITCH_180_YAW_90", "PITCH_180_YAW_270", "ROLL_90_PITCH_90", "ROLL_180_PITCH_90", "ROLL_270_PITCH_90", "ROLL_90_PITCH_180", "ROLL_270_PITCH_180", "ROLL_90_PITCH_270", "ROLL_180_PITCH_270", "ROLL_270_PITCH_270", "ROLL_90_PITCH_180_YAW_90", "ROLL_90_YAW_270", "ROLL_90_PITCH_68_YAW_293", "PITCH_315", "ROLL_90_PITCH_315", "CUSTOM"]

MAV_MISSION_TYPE = {
    0: "MISSION", "MISSION": 0,
    1: "FENCE", "FENCE": 1,
    2: "RALLY", "RALLY": 2,
    255: "ALL", "ALL": 255
}
MavMissionType = Literal["MISSION", "FENCE", "RALLY", "ALL"]

MAV_ESTIMATOR_TYPE = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "NAIVE", "NAIVE": 1,
    2: "VISION", "VISION": 2,
    3: "VIO", "VIO": 3,
    4: "GPS", "GPS": 4,
    5: "GPS_INS", "GPS_INS": 5,
    6: "MOCAP", "MOCAP": 6,
    7: "LIDAR", "LIDAR": 7,
    8: "AUTOPILOT", "AUTOPILOT": 8
}
MavEstimatorType = Literal["UNKNOWN", "NAIVE", "VISION", "VIO", "GPS", "GPS_INS", "MOCAP", "LIDAR", "AUTOPILOT"]

MAV_BATTERY_TYPE = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "LIPO", "LIPO": 1,
    2: "LIFE", "LIFE": 2,
    3: "LION", "LION": 3,
    4: "NIMH", "NIMH": 4
}
MavBatteryType = Literal["UNKNOWN", "LIPO", "LIFE", "LION", "NIMH"]

MAV_BATTERY_FUNCTION = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "ALL", "ALL": 1,
    2: "PROPULSION", "PROPULSION": 2,
    3: "AVIONICS", "AVIONICS": 3,
    4: "PAYLOAD", "PAYLOAD": 4
}
MavBatteryFunction = Literal["UNKNOWN", "ALL", "PROPULSION", "AVIONICS", "PAYLOAD"]

MAV_BATTERY_CHARGE_STATE = {
    0: "UNDEFINED", "UNDEFINED": 0,
    1: "OK", "OK": 1,
    2: "LOW", "LOW": 2,
    3: "CRITICAL", "CRITICAL": 3,
    4: "EMERGENCY", "EMERGENCY": 4,
    5: "FAILED", "FAILED": 5,
    6: "UNHEALTHY", "UNHEALTHY": 6,
    7: "CHARGING", "CHARGING": 7
}
MavBatteryChargeState = Literal["UNDEFINED", "OK", "LOW", "CRITICAL", "EMERGENCY", "FAILED", "UNHEALTHY", "CHARGING"]

MAV_BATTERY_MODE = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "AUTO_DISCHARGING", "AUTO_DISCHARGING": 1,
    2: "HOT_SWAP", "HOT_SWAP": 2
}
MavBatteryMode = Literal["UNKNOWN", "AUTO_DISCHARGING", "HOT_SWAP"]

MAV_BATTERY_FAULT = {
    1: "MAV_BATTERY_FAULT_DEEP_DISCHARGE", "MAV_BATTERY_FAULT_DEEP_DISCHARGE": 1,
    2: "MAV_BATTERY_FAULT_SPIKES", "MAV_BATTERY_FAULT_SPIKES": 2,
    4: "MAV_BATTERY_FAULT_CELL_FAIL", "MAV_BATTERY_FAULT_CELL_FAIL": 4,
    8: "MAV_BATTERY_FAULT_OVER_CURRENT", "MAV_BATTERY_FAULT_OVER_CURRENT": 8,
    16: "MAV_BATTERY_FAULT_OVER_TEMPERATURE", "MAV_BATTERY_FAULT_OVER_TEMPERATURE": 16,
    32: "MAV_BATTERY_FAULT_UNDER_TEMPERATURE", "MAV_BATTERY_FAULT_UNDER_TEMPERATURE": 32,
    64: "MAV_BATTERY_FAULT_INCOMPATIBLE_VOLTAGE", "MAV_BATTERY_FAULT_INCOMPATIBLE_VOLTAGE": 64,
    128: "MAV_BATTERY_FAULT_INCOMPATIBLE_FIRMWARE", "MAV_BATTERY_FAULT_INCOMPATIBLE_FIRMWARE": 128,
    256: "BATTERY_FAULT_INCOMPATIBLE_CELLS_CONFIGURATION", "BATTERY_FAULT_INCOMPATIBLE_CELLS_CONFIGURATION": 256
}
MavBatteryFault = Literal[
    "MAV_BATTERY_FAULT_DEEP_DISCHARGE", "MAV_BATTERY_FAULT_SPIKES", "MAV_BATTERY_FAULT_CELL_FAIL", "MAV_BATTERY_FAULT_OVER_CURRENT", "MAV_BATTERY_FAULT_OVER_TEMPERATURE", "MAV_BATTERY_FAULT_UNDER_TEMPERATURE", "MAV_BATTERY_FAULT_INCOMPATIBLE_VOLTAGE", "MAV_BATTERY_FAULT_INCOMPATIBLE_FIRMWARE", "BATTERY_FAULT_INCOMPATIBLE_CELLS_CONFIGURATION"]

MAV_FUEL_TYPE = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "LIQUID", "LIQUID": 1,
    2: "GAS", "GAS": 2
}
MavFuelType = Literal["UNKNOWN", "LIQUID", "GAS"]

MAV_GENERATOR_STATUS_FLAG = {
    1: "OFF", "OFF": 1,
    2: "READY", "READY": 2,
    4: "GENERATING", "GENERATING": 4,
    8: "CHARGING", "CHARGING": 8,
    16: "REDUCED_POWER", "REDUCED_POWER": 16,
    32: "MAXPOWER", "MAXPOWER": 32,
    64: "OVERTEMP_WARNING", "OVERTEMP_WARNING": 64,
    128: "OVERTEMP_FAULT", "OVERTEMP_FAULT": 128,
    256: "ELECTRONICS_OVERTEMP_WARNING", "ELECTRONICS_OVERTEMP_WARNING": 256,
    512: "ELECTRONICS_OVERTEMP_FAULT", "ELECTRONICS_OVERTEMP_FAULT": 512,
    1024: "ELECTRONICS_FAULT", "ELECTRONICS_FAULT": 1024,
    2048: "POWERSOURCE_FAULT", "POWERSOURCE_FAULT": 2048,
    4096: "COMMUNICATION_WARNING", "COMMUNICATION_WARNING": 4096,
    8192: "COOLING_WARNING", "COOLING_WARNING": 8192,
    16384: "POWER_RAIL_FAULT", "POWER_RAIL_FAULT": 16384,
    32768: "OVERCURRENT_FAULT", "OVERCURRENT_FAULT": 32768,
    65536: "BATTERY_OVERCHARGE_CURRENT_FAULT", "BATTERY_OVERCHARGE_CURRENT_FAULT": 65536,
    131072: "OVERVOLTAGE_FAULT", "OVERVOLTAGE_FAULT": 131072,
    262144: "BATTERY_UNDERVOLT_FAULT", "BATTERY_UNDERVOLT_FAULT": 262144,
    524288: "START_INHIBITED", "START_INHIBITED": 524288,
    1048576: "MAINTENANCE_REQUIRED", "MAINTENANCE_REQUIRED": 1048576,
    2097152: "WARMING_UP", "WARMING_UP": 2097152,
    4194304: "IDLE", "IDLE": 4194304
}
MavGeneratorStatusFlag = Literal[
    "OFF", "READY", "GENERATING", "CHARGING", "REDUCED_POWER", "MAXPOWER", "OVERTEMP_WARNING", "OVERTEMP_FAULT", "ELECTRONICS_OVERTEMP_WARNING", "ELECTRONICS_OVERTEMP_FAULT", "ELECTRONICS_FAULT", "POWERSOURCE_FAULT", "COMMUNICATION_WARNING", "COOLING_WARNING", "POWER_RAIL_FAULT", "OVERCURRENT_FAULT", "BATTERY_OVERCHARGE_CURRENT_FAULT", "OVERVOLTAGE_FAULT", "BATTERY_UNDERVOLT_FAULT", "START_INHIBITED", "MAINTENANCE_REQUIRED", "WARMING_UP", "IDLE"]

MAV_VTOL_STATE = {
    0: "UNDEFINED", "UNDEFINED": 0,
    1: "TRANSITION_TO_FW", "TRANSITION_TO_FW": 1,
    2: "TRANSITION_TO_MC", "TRANSITION_TO_MC": 2,
    3: "MC", "MC": 3,
    4: "FW", "FW": 4
}
MavVtolState = Literal["UNDEFINED", "TRANSITION_TO_FW", "TRANSITION_TO_MC", "MC", "FW"]

MAV_LANDED_STATE = {
    0: "UNDEFINED", "UNDEFINED": 0,
    1: "ON_GROUND", "ON_GROUND": 1,
    2: "IN_AIR", "IN_AIR": 2,
    3: "TAKEOFF", "TAKEOFF": 3,
    4: "LANDING", "LANDING": 4
}
MavLandedState = Literal["UNDEFINED", "ON_GROUND", "IN_AIR", "TAKEOFF", "LANDING"]

ADSB_ALTITUDE_TYPE = {
    0: "PRESSURE_QNH", "PRESSURE_QNH": 0,
    1: "GEOMETRIC", "GEOMETRIC": 1
}
AdsbAltitudeType = Literal["PRESSURE_QNH", "GEOMETRIC"]

ADSB_EMITTER_TYPE = {
    0: "NO_INFO", "NO_INFO": 0,
    1: "LIGHT", "LIGHT": 1,
    2: "SMALL", "SMALL": 2,
    3: "LARGE", "LARGE": 3,
    4: "HIGH_VORTEX_LARGE", "HIGH_VORTEX_LARGE": 4,
    5: "HEAVY", "HEAVY": 5,
    6: "HIGHLY_MANUV", "HIGHLY_MANUV": 6,
    7: "ROTOCRAFT", "ROTOCRAFT": 7,
    8: "UNASSIGNED", "UNASSIGNED": 8,
    9: "GLIDER", "GLIDER": 9,
    10: "LIGHTER_AIR", "LIGHTER_AIR": 10,
    11: "PARACHUTE", "PARACHUTE": 11,
    12: "ULTRA_LIGHT", "ULTRA_LIGHT": 12,
    13: "UNASSIGNED2", "UNASSIGNED2": 13,
    14: "UAV", "UAV": 14,
    15: "SPACE", "SPACE": 15,
    16: "UNASSGINED3", "UNASSGINED3": 16,
    17: "EMERGENCY_SURFACE", "EMERGENCY_SURFACE": 17,
    18: "SERVICE_SURFACE", "SERVICE_SURFACE": 18,
    19: "POINT_OBSTACLE", "POINT_OBSTACLE": 19
}
AdsbEmitterType = Literal[
    "NO_INFO", "LIGHT", "SMALL", "LARGE", "HIGH_VORTEX_LARGE", "HEAVY", "HIGHLY_MANUV", "ROTOCRAFT", "UNASSIGNED", "GLIDER", "LIGHTER_AIR", "PARACHUTE", "ULTRA_LIGHT", "UNASSIGNED2", "UAV", "SPACE", "UNASSGINED3", "EMERGENCY_SURFACE", "SERVICE_SURFACE", "POINT_OBSTACLE"]

ADSB_FLAGS = {
    1: "VALID_COORDS", "VALID_COORDS": 1,
    2: "VALID_ALTITUDE", "VALID_ALTITUDE": 2,
    4: "VALID_HEADING", "VALID_HEADING": 4,
    8: "VALID_VELOCITY", "VALID_VELOCITY": 8,
    16: "VALID_CALLSIGN", "VALID_CALLSIGN": 16,
    32: "VALID_SQUAWK", "VALID_SQUAWK": 32,
    64: "SIMULATED", "SIMULATED": 64,
    128: "VERTICAL_VELOCITY_VALID", "VERTICAL_VELOCITY_VALID": 128,
    256: "BARO_VALID", "BARO_VALID": 256,
    32768: "SOURCE_UAT", "SOURCE_UAT": 32768
}
AdsbFlags = Literal[
    "VALID_COORDS", "VALID_ALTITUDE", "VALID_HEADING", "VALID_VELOCITY", "VALID_CALLSIGN", "VALID_SQUAWK", "SIMULATED", "VERTICAL_VELOCITY_VALID", "BARO_VALID", "SOURCE_UAT"]

MAV_DO_REPOSITION_FLAGS = {
    1: "CHANGE_MODE", "CHANGE_MODE": 1,
    2: "RELATIVE_YAW", "RELATIVE_YAW": 2
}
MavDoRepositionFlags = Literal["CHANGE_MODE", "RELATIVE_YAW"]

SPEED_TYPE = {
    0: "AIRSPEED", "AIRSPEED": 0,
    1: "GROUNDSPEED", "GROUNDSPEED": 1,
    2: "CLIMB_SPEED", "CLIMB_SPEED": 2,
    3: "DESCENT_SPEED", "DESCENT_SPEED": 3
}
SpeedType = Literal["AIRSPEED", "GROUNDSPEED", "CLIMB_SPEED", "DESCENT_SPEED"]

ESTIMATOR_STATUS_FLAGS = {
    1: "ATTITUDE", "ATTITUDE": 1,
    2: "VELOCITY_HORIZ", "VELOCITY_HORIZ": 2,
    4: "VELOCITY_VERT", "VELOCITY_VERT": 4,
    8: "POS_HORIZ_REL", "POS_HORIZ_REL": 8,
    16: "POS_HORIZ_ABS", "POS_HORIZ_ABS": 16,
    32: "POS_VERT_ABS", "POS_VERT_ABS": 32,
    64: "POS_VERT_AGL", "POS_VERT_AGL": 64,
    128: "CONST_POS_MODE", "CONST_POS_MODE": 128,
    256: "PRED_POS_HORIZ_REL", "PRED_POS_HORIZ_REL": 256,
    512: "PRED_POS_HORIZ_ABS", "PRED_POS_HORIZ_ABS": 512,
    1024: "GPS_GLITCH", "GPS_GLITCH": 1024,
    2048: "ACCEL_ERROR", "ACCEL_ERROR": 2048
}
EstimatorStatusFlags = Literal[
    "ATTITUDE", "VELOCITY_HORIZ", "VELOCITY_VERT", "POS_HORIZ_REL", "POS_HORIZ_ABS", "POS_VERT_ABS", "POS_VERT_AGL", "CONST_POS_MODE", "PRED_POS_HORIZ_REL", "PRED_POS_HORIZ_ABS", "GPS_GLITCH", "ACCEL_ERROR"]

MOTOR_TEST_ORDER = {
    0: "DEFAULT", "DEFAULT": 0,
    1: "SEQUENCE", "SEQUENCE": 1,
    2: "BOARD", "BOARD": 2
}
MotorTestOrder = Literal["DEFAULT", "SEQUENCE", "BOARD"]

MOTOR_TEST_THROTTLE_TYPE = {
    0: "THROTTLE_PERCENT", "THROTTLE_PERCENT": 0,
    1: "THROTTLE_PWM", "THROTTLE_PWM": 1,
    2: "THROTTLE_PILOT", "THROTTLE_PILOT": 2,
    3: "COMPASS_CAL", "COMPASS_CAL": 3
}
MotorTestThrottleType = Literal["THROTTLE_PERCENT", "THROTTLE_PWM", "THROTTLE_PILOT", "COMPASS_CAL"]

GPS_INPUT_IGNORE_FLAGS = {
    1: "ALT", "ALT": 1,
    2: "HDOP", "HDOP": 2,
    4: "VDOP", "VDOP": 4,
    8: "VEL_HORIZ", "VEL_HORIZ": 8,
    16: "VEL_VERT", "VEL_VERT": 16,
    32: "SPEED_ACCURACY", "SPEED_ACCURACY": 32,
    64: "HORIZONTAL_ACCURACY", "HORIZONTAL_ACCURACY": 64,
    128: "VERTICAL_ACCURACY", "VERTICAL_ACCURACY": 128
}
GpsInputIgnoreFlags = Literal[
    "ALT", "HDOP", "VDOP", "VEL_HORIZ", "VEL_VERT", "SPEED_ACCURACY", "HORIZONTAL_ACCURACY", "VERTICAL_ACCURACY"]

MAV_COLLISION_ACTION = {
    0: "NONE", "NONE": 0,
    1: "REPORT", "REPORT": 1,
    2: "ASCEND_OR_DESCEND", "ASCEND_OR_DESCEND": 2,
    3: "MOVE_HORIZONTALLY", "MOVE_HORIZONTALLY": 3,
    4: "MOVE_PERPENDICULAR", "MOVE_PERPENDICULAR": 4,
    5: "RTL", "RTL": 5,
    6: "HOVER", "HOVER": 6
}
MavCollisionAction = Literal[
    "NONE", "REPORT", "ASCEND_OR_DESCEND", "MOVE_HORIZONTALLY", "MOVE_PERPENDICULAR", "RTL", "HOVER"]

MAV_COLLISION_THREAT_LEVEL = {
    0: "NONE", "NONE": 0,
    1: "LOW", "LOW": 1,
    2: "HIGH", "HIGH": 2
}
MavCollisionThreatLevel = Literal["NONE", "LOW", "HIGH"]

MAV_COLLISION_SRC = {
    0: "ADSB", "ADSB": 0,
    1: "MAVLINK_GPS_GLOBAL_INT", "MAVLINK_GPS_GLOBAL_INT": 1
}
MavCollisionSrc = Literal["ADSB", "MAVLINK_GPS_GLOBAL_INT"]

GPS_FIX_TYPE = {
    0: "NO_GPS", "NO_GPS": 0,
    1: "NO_FIX", "NO_FIX": 1,
    2: "2D_FIX", "2D_FIX": 2,
    3: "3D_FIX", "3D_FIX": 3,
    4: "DGPS", "DGPS": 4,
    5: "RTK_FLOAT", "RTK_FLOAT": 5,
    6: "RTK_FIXED", "RTK_FIXED": 6,
    7: "STATIC", "STATIC": 7,
    8: "PPP", "PPP": 8
}
GpsFixType = Literal["NO_GPS", "NO_FIX", "2D_FIX", "3D_FIX", "DGPS", "RTK_FLOAT", "RTK_FIXED", "STATIC", "PPP"]

RTK_BASELINE_COORDINATE_SYSTEM = {
    0: "ECEF", "ECEF": 0,
    1: "NED", "NED": 1
}
RtkBaselineCoordinateSystem = Literal["ECEF", "NED"]

LANDING_TARGET_TYPE = {
    0: "LIGHT_BEACON", "LIGHT_BEACON": 0,
    1: "RADIO_BEACON", "RADIO_BEACON": 1,
    2: "VISION_FIDUCIAL", "VISION_FIDUCIAL": 2,
    3: "VISION_OTHER", "VISION_OTHER": 3
}
LandingTargetType = Literal["LIGHT_BEACON", "RADIO_BEACON", "VISION_FIDUCIAL", "VISION_OTHER"]

VTOL_TRANSITION_HEADING = {
    0: "VEHICLE_DEFAULT", "VEHICLE_DEFAULT": 0,
    1: "NEXT_WAYPOINT", "NEXT_WAYPOINT": 1,
    2: "TAKEOFF", "TAKEOFF": 2,
    3: "SPECIFIED", "SPECIFIED": 3,
    4: "ANY", "ANY": 4
}
VtolTransitionHeading = Literal["VEHICLE_DEFAULT", "NEXT_WAYPOINT", "TAKEOFF", "SPECIFIED", "ANY"]

CAMERA_CAP_FLAGS = {
    1: "CAPTURE_VIDEO", "CAPTURE_VIDEO": 1,
    2: "CAPTURE_IMAGE", "CAPTURE_IMAGE": 2,
    4: "HAS_MODES", "HAS_MODES": 4,
    8: "CAN_CAPTURE_IMAGE_IN_VIDEO_MODE", "CAN_CAPTURE_IMAGE_IN_VIDEO_MODE": 8,
    16: "CAN_CAPTURE_VIDEO_IN_IMAGE_MODE", "CAN_CAPTURE_VIDEO_IN_IMAGE_MODE": 16,
    32: "HAS_IMAGE_SURVEY_MODE", "HAS_IMAGE_SURVEY_MODE": 32,
    64: "HAS_BASIC_ZOOM", "HAS_BASIC_ZOOM": 64,
    128: "HAS_BASIC_FOCUS", "HAS_BASIC_FOCUS": 128,
    256: "HAS_VIDEO_STREAM", "HAS_VIDEO_STREAM": 256,
    512: "HAS_TRACKING_POINT", "HAS_TRACKING_POINT": 512,
    1024: "HAS_TRACKING_RECTANGLE", "HAS_TRACKING_RECTANGLE": 1024,
    2048: "HAS_TRACKING_GEO_STATUS", "HAS_TRACKING_GEO_STATUS": 2048,
    4096: "HAS_THERMAL_RANGE", "HAS_THERMAL_RANGE": 4096,
    8192: "HAS_MTI", "HAS_MTI": 8192
}
CameraCapFlags = Literal[
    "CAPTURE_VIDEO", "CAPTURE_IMAGE", "HAS_MODES", "CAN_CAPTURE_IMAGE_IN_VIDEO_MODE", "CAN_CAPTURE_VIDEO_IN_IMAGE_MODE", "HAS_IMAGE_SURVEY_MODE", "HAS_BASIC_ZOOM", "HAS_BASIC_FOCUS", "HAS_VIDEO_STREAM", "HAS_TRACKING_POINT", "HAS_TRACKING_RECTANGLE", "HAS_TRACKING_GEO_STATUS", "HAS_THERMAL_RANGE", "HAS_MTI"]

VIDEO_STREAM_STATUS_FLAGS = {
    1: "RUNNING", "RUNNING": 1,
    2: "THERMAL", "THERMAL": 2,
    4: "THERMAL_RANGE_ENABLED", "THERMAL_RANGE_ENABLED": 4
}
VideoStreamStatusFlags = Literal["RUNNING", "THERMAL", "THERMAL_RANGE_ENABLED"]

VIDEO_STREAM_TYPE = {
    0: "RTSP", "RTSP": 0,
    1: "RTPUDP", "RTPUDP": 1,
    2: "TCP_MPEG", "TCP_MPEG": 2,
    3: "MPEG_TS", "MPEG_TS": 3
}
VideoStreamType = Literal["RTSP", "RTPUDP", "TCP_MPEG", "MPEG_TS"]

VIDEO_STREAM_ENCODING = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "H264", "H264": 1,
    2: "H265", "H265": 2
}
VideoStreamEncoding = Literal["UNKNOWN", "H264", "H265"]

CAMERA_TRACKING_STATUS_FLAGS = {
    0: "IDLE", "IDLE": 0,
    1: "ACTIVE", "ACTIVE": 1,
    2: "ERROR", "ERROR": 2,
    4: "MTI", "MTI": 4,
    8: "COASTING", "COASTING": 8
}
CameraTrackingStatusFlags = Literal["IDLE", "ACTIVE", "ERROR", "MTI", "COASTING"]

CAMERA_TRACKING_MODE = {
    0: "NONE", "NONE": 0,
    1: "POINT", "POINT": 1,
    2: "RECTANGLE", "RECTANGLE": 2
}
CameraTrackingMode = Literal["NONE", "POINT", "RECTANGLE"]

CAMERA_TRACKING_TARGET_DATA = {
    1: "EMBEDDED", "EMBEDDED": 1,
    2: "RENDERED", "RENDERED": 2,
    4: "IN_STATUS", "IN_STATUS": 4
}
CameraTrackingTargetData = Literal["EMBEDDED", "RENDERED", "IN_STATUS"]

CAMERA_ZOOM_TYPE = {
    0: "STEP", "STEP": 0,
    1: "CONTINUOUS", "CONTINUOUS": 1,
    2: "RANGE", "RANGE": 2,
    3: "FOCAL_LENGTH", "FOCAL_LENGTH": 3,
    4: "HORIZONTAL_FOV", "HORIZONTAL_FOV": 4
}
CameraZoomType = Literal["STEP", "CONTINUOUS", "RANGE", "FOCAL_LENGTH", "HORIZONTAL_FOV"]

SET_FOCUS_TYPE = {
    0: "STEP", "STEP": 0,
    1: "CONTINUOUS", "CONTINUOUS": 1,
    2: "RANGE", "RANGE": 2,
    3: "METERS", "METERS": 3,
    4: "AUTO", "AUTO": 4,
    5: "AUTO_SINGLE", "AUTO_SINGLE": 5,
    6: "AUTO_CONTINUOUS", "AUTO_CONTINUOUS": 6
}
SetFocusType = Literal["STEP", "CONTINUOUS", "RANGE", "METERS", "AUTO", "AUTO_SINGLE", "AUTO_CONTINUOUS"]

CAMERA_SOURCE = {
    0: "DEFAULT", "DEFAULT": 0,
    1: "RGB", "RGB": 1,
    2: "IR", "IR": 2,
    3: "NDVI", "NDVI": 3
}
CameraSource = Literal["DEFAULT", "RGB", "IR", "NDVI"]

PARAM_ACK = {
    0: "ACCEPTED", "ACCEPTED": 0,
    1: "VALUE_UNSUPPORTED", "VALUE_UNSUPPORTED": 1,
    2: "FAILED", "FAILED": 2,
    3: "IN_PROGRESS", "IN_PROGRESS": 3
}
ParamAck = Literal["ACCEPTED", "VALUE_UNSUPPORTED", "FAILED", "IN_PROGRESS"]

CAMERA_MODE = {
    0: "IMAGE", "IMAGE": 0,
    1: "VIDEO", "VIDEO": 1,
    2: "IMAGE_SURVEY", "IMAGE_SURVEY": 2
}
CameraMode = Literal["IMAGE", "VIDEO", "IMAGE_SURVEY"]

MAV_ARM_AUTH_DENIED_REASON = {
    0: "GENERIC", "GENERIC": 0,
    1: "NONE", "NONE": 1,
    2: "INVALID_WAYPOINT", "INVALID_WAYPOINT": 2,
    3: "TIMEOUT", "TIMEOUT": 3,
    4: "AIRSPACE_IN_USE", "AIRSPACE_IN_USE": 4,
    5: "BAD_WEATHER", "BAD_WEATHER": 5
}
MavArmAuthDeniedReason = Literal["GENERIC", "NONE", "INVALID_WAYPOINT", "TIMEOUT", "AIRSPACE_IN_USE", "BAD_WEATHER"]

RC_TYPE = {
    0: "SPEKTRUM", "SPEKTRUM": 0,
    1: "CRSF", "CRSF": 1
}
RcType = Literal["SPEKTRUM", "CRSF"]

RC_SUB_TYPE = {
    0: "2", "2": 0,
    1: "X", "X": 1,
    2: "X8", "X8": 2
}
RcSubType = Literal["2", "X", "X8"]

POSITION_TARGET_TYPEMASK = {
    1: "X_IGNORE", "X_IGNORE": 1,
    2: "Y_IGNORE", "Y_IGNORE": 2,
    4: "Z_IGNORE", "Z_IGNORE": 4,
    8: "VX_IGNORE", "VX_IGNORE": 8,
    16: "VY_IGNORE", "VY_IGNORE": 16,
    32: "VZ_IGNORE", "VZ_IGNORE": 32,
    64: "AX_IGNORE", "AX_IGNORE": 64,
    128: "AY_IGNORE", "AY_IGNORE": 128,
    256: "AZ_IGNORE", "AZ_IGNORE": 256,
    512: "FORCE_SET", "FORCE_SET": 512,
    1024: "YAW_IGNORE", "YAW_IGNORE": 1024,
    2048: "YAW_RATE_IGNORE", "YAW_RATE_IGNORE": 2048
}
PositionTargetTypemask = Literal[
    "X_IGNORE", "Y_IGNORE", "Z_IGNORE", "VX_IGNORE", "VY_IGNORE", "VZ_IGNORE", "AX_IGNORE", "AY_IGNORE", "AZ_IGNORE", "FORCE_SET", "YAW_IGNORE", "YAW_RATE_IGNORE"]

ATTITUDE_TARGET_TYPEMASK = {
    1: "BODY_ROLL_RATE_IGNORE", "BODY_ROLL_RATE_IGNORE": 1,
    2: "BODY_PITCH_RATE_IGNORE", "BODY_PITCH_RATE_IGNORE": 2,
    4: "BODY_YAW_RATE_IGNORE", "BODY_YAW_RATE_IGNORE": 4,
    32: "THRUST_BODY_SET", "THRUST_BODY_SET": 32,
    64: "THROTTLE_IGNORE", "THROTTLE_IGNORE": 64,
    128: "ATTITUDE_IGNORE", "ATTITUDE_IGNORE": 128
}
AttitudeTargetTypemask = Literal[
    "BODY_ROLL_RATE_IGNORE", "BODY_PITCH_RATE_IGNORE", "BODY_YAW_RATE_IGNORE", "THRUST_BODY_SET", "THROTTLE_IGNORE", "ATTITUDE_IGNORE"]

UTM_FLIGHT_STATE = {
    1: "UNKNOWN", "UNKNOWN": 1,
    2: "GROUND", "GROUND": 2,
    3: "AIRBORNE", "AIRBORNE": 3,
    16: "EMERGENCY", "EMERGENCY": 16,
    32: "NOCTRL", "NOCTRL": 32
}
UtmFlightState = Literal["UNKNOWN", "GROUND", "AIRBORNE", "EMERGENCY", "NOCTRL"]

UTM_DATA_AVAIL_FLAGS = {
    1: "TIME_VALID", "TIME_VALID": 1,
    2: "UAS_ID_AVAILABLE", "UAS_ID_AVAILABLE": 2,
    4: "POSITION_AVAILABLE", "POSITION_AVAILABLE": 4,
    8: "ALTITUDE_AVAILABLE", "ALTITUDE_AVAILABLE": 8,
    16: "RELATIVE_ALTITUDE_AVAILABLE", "RELATIVE_ALTITUDE_AVAILABLE": 16,
    32: "HORIZONTAL_VELO_AVAILABLE", "HORIZONTAL_VELO_AVAILABLE": 32,
    64: "VERTICAL_VELO_AVAILABLE", "VERTICAL_VELO_AVAILABLE": 64,
    128: "NEXT_WAYPOINT_AVAILABLE", "NEXT_WAYPOINT_AVAILABLE": 128
}
UtmDataAvailFlags = Literal[
    "TIME_VALID", "UAS_ID_AVAILABLE", "POSITION_AVAILABLE", "ALTITUDE_AVAILABLE", "RELATIVE_ALTITUDE_AVAILABLE", "HORIZONTAL_VELO_AVAILABLE", "VERTICAL_VELO_AVAILABLE", "NEXT_WAYPOINT_AVAILABLE"]

CELLULAR_STATUS_FLAG = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "FAILED", "FAILED": 1,
    2: "INITIALIZING", "INITIALIZING": 2,
    3: "LOCKED", "LOCKED": 3,
    4: "DISABLED", "DISABLED": 4,
    5: "DISABLING", "DISABLING": 5,
    6: "ENABLING", "ENABLING": 6,
    7: "ENABLED", "ENABLED": 7,
    8: "SEARCHING", "SEARCHING": 8,
    9: "REGISTERED", "REGISTERED": 9,
    10: "DISCONNECTING", "DISCONNECTING": 10,
    11: "CONNECTING", "CONNECTING": 11,
    12: "CONNECTED", "CONNECTED": 12
}
CellularStatusFlag = Literal[
    "UNKNOWN", "FAILED", "INITIALIZING", "LOCKED", "DISABLED", "DISABLING", "ENABLING", "ENABLED", "SEARCHING", "REGISTERED", "DISCONNECTING", "CONNECTING", "CONNECTED"]

CELLULAR_NETWORK_FAILED_REASON = {
    0: "NONE", "NONE": 0,
    1: "UNKNOWN", "UNKNOWN": 1,
    2: "SIM_MISSING", "SIM_MISSING": 2,
    3: "SIM_ERROR", "SIM_ERROR": 3
}
CellularNetworkFailedReason = Literal["NONE", "UNKNOWN", "SIM_MISSING", "SIM_ERROR"]

CELLULAR_NETWORK_RADIO_TYPE = {
    0: "NONE", "NONE": 0,
    1: "GSM", "GSM": 1,
    2: "CDMA", "CDMA": 2,
    3: "WCDMA", "WCDMA": 3,
    4: "LTE", "LTE": 4
}
CellularNetworkRadioType = Literal["NONE", "GSM", "CDMA", "WCDMA", "LTE"]

PRECISION_LAND_MODE = {
    0: "DISABLED", "DISABLED": 0,
    1: "OPPORTUNISTIC", "OPPORTUNISTIC": 1,
    2: "REQUIRED", "REQUIRED": 2
}
PrecisionLandMode = Literal["DISABLED", "OPPORTUNISTIC", "REQUIRED"]

PARACHUTE_ACTION = {
    0: "DISABLE", "DISABLE": 0,
    1: "ENABLE", "ENABLE": 1,
    2: "RELEASE", "RELEASE": 2
}
ParachuteAction = Literal["DISABLE", "ENABLE", "RELEASE"]

MAV_TUNNEL_PAYLOAD_TYPE = {
    0: "UNKNOWN", "UNKNOWN": 0,
    200: "STORM32_RESERVED0", "STORM32_RESERVED0": 200,
    201: "STORM32_RESERVED1", "STORM32_RESERVED1": 201,
    202: "STORM32_RESERVED2", "STORM32_RESERVED2": 202,
    203: "STORM32_RESERVED3", "STORM32_RESERVED3": 203,
    204: "STORM32_RESERVED4", "STORM32_RESERVED4": 204,
    205: "STORM32_RESERVED5", "STORM32_RESERVED5": 205,
    206: "STORM32_RESERVED6", "STORM32_RESERVED6": 206,
    207: "STORM32_RESERVED7", "STORM32_RESERVED7": 207,
    208: "STORM32_RESERVED8", "STORM32_RESERVED8": 208,
    209: "STORM32_RESERVED9", "STORM32_RESERVED9": 209,
    210: "MODALAI_REMOTE_OSD", "MODALAI_REMOTE_OSD": 210,
    211: "MODALAI_ESC_UART_PASSTHRU", "MODALAI_ESC_UART_PASSTHRU": 211,
    212: "MODALAI_IO_UART_PASSTHRU", "MODALAI_IO_UART_PASSTHRU": 212
}
MavTunnelPayloadType = Literal[
    "UNKNOWN", "STORM32_RESERVED0", "STORM32_RESERVED1", "STORM32_RESERVED2", "STORM32_RESERVED3", "STORM32_RESERVED4", "STORM32_RESERVED5", "STORM32_RESERVED6", "STORM32_RESERVED7", "STORM32_RESERVED8", "STORM32_RESERVED9", "MODALAI_REMOTE_OSD", "MODALAI_ESC_UART_PASSTHRU", "MODALAI_IO_UART_PASSTHRU"]

MAV_ODID_ID_TYPE = {
    0: "NONE", "NONE": 0,
    1: "SERIAL_NUMBER", "SERIAL_NUMBER": 1,
    2: "CAA_REGISTRATION_ID", "CAA_REGISTRATION_ID": 2,
    3: "UTM_ASSIGNED_UUID", "UTM_ASSIGNED_UUID": 3,
    4: "SPECIFIC_SESSION_ID", "SPECIFIC_SESSION_ID": 4
}
MavOdidIdType = Literal["NONE", "SERIAL_NUMBER", "CAA_REGISTRATION_ID", "UTM_ASSIGNED_UUID", "SPECIFIC_SESSION_ID"]

MAV_ODID_UA_TYPE = {
    0: "NONE", "NONE": 0,
    1: "AEROPLANE", "AEROPLANE": 1,
    2: "HELICOPTER_OR_MULTIROTOR", "HELICOPTER_OR_MULTIROTOR": 2,
    3: "GYROPLANE", "GYROPLANE": 3,
    4: "HYBRID_LIFT", "HYBRID_LIFT": 4,
    5: "ORNITHOPTER", "ORNITHOPTER": 5,
    6: "GLIDER", "GLIDER": 6,
    7: "KITE", "KITE": 7,
    8: "FREE_BALLOON", "FREE_BALLOON": 8,
    9: "CAPTIVE_BALLOON", "CAPTIVE_BALLOON": 9,
    10: "AIRSHIP", "AIRSHIP": 10,
    11: "FREE_FALL_PARACHUTE", "FREE_FALL_PARACHUTE": 11,
    12: "ROCKET", "ROCKET": 12,
    13: "TETHERED_POWERED_AIRCRAFT", "TETHERED_POWERED_AIRCRAFT": 13,
    14: "GROUND_OBSTACLE", "GROUND_OBSTACLE": 14,
    15: "OTHER", "OTHER": 15
}
MavOdidUaType = Literal[
    "NONE", "AEROPLANE", "HELICOPTER_OR_MULTIROTOR", "GYROPLANE", "HYBRID_LIFT", "ORNITHOPTER", "GLIDER", "KITE", "FREE_BALLOON", "CAPTIVE_BALLOON", "AIRSHIP", "FREE_FALL_PARACHUTE", "ROCKET", "TETHERED_POWERED_AIRCRAFT", "GROUND_OBSTACLE", "OTHER"]

MAV_ODID_STATUS = {
    0: "UNDECLARED", "UNDECLARED": 0,
    1: "GROUND", "GROUND": 1,
    2: "AIRBORNE", "AIRBORNE": 2,
    3: "EMERGENCY", "EMERGENCY": 3,
    4: "REMOTE_ID_SYSTEM_FAILURE", "REMOTE_ID_SYSTEM_FAILURE": 4
}
MavOdidStatus = Literal["UNDECLARED", "GROUND", "AIRBORNE", "EMERGENCY", "REMOTE_ID_SYSTEM_FAILURE"]

MAV_ODID_HEIGHT_REF = {
    0: "TAKEOFF", "TAKEOFF": 0,
    1: "GROUND", "GROUND": 1
}
MavOdidHeightRef = Literal["TAKEOFF", "GROUND"]

MAV_ODID_HOR_ACC = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "10NM", "10NM": 1,
    2: "4NM", "4NM": 2,
    3: "2NM", "2NM": 3,
    4: "1NM", "1NM": 4,
    5: "0_5NM", "0_5NM": 5,
    6: "0_3NM", "0_3NM": 6,
    7: "0_1NM", "0_1NM": 7,
    8: "0_05NM", "0_05NM": 8,
    9: "30_METER", "30_METER": 9,
    10: "10_METER", "10_METER": 10,
    11: "3_METER", "3_METER": 11,
    12: "1_METER", "1_METER": 12
}
MavOdidHorAcc = Literal[
    "UNKNOWN", "10NM", "4NM", "2NM", "1NM", "0_5NM", "0_3NM", "0_1NM", "0_05NM", "30_METER", "10_METER", "3_METER", "1_METER"]

MAV_ODID_VER_ACC = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "150_METER", "150_METER": 1,
    2: "45_METER", "45_METER": 2,
    3: "25_METER", "25_METER": 3,
    4: "10_METER", "10_METER": 4,
    5: "3_METER", "3_METER": 5,
    6: "1_METER", "1_METER": 6
}
MavOdidVerAcc = Literal["UNKNOWN", "150_METER", "45_METER", "25_METER", "10_METER", "3_METER", "1_METER"]

MAV_ODID_SPEED_ACC = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "10_METERS_PER_SECOND", "10_METERS_PER_SECOND": 1,
    2: "3_METERS_PER_SECOND", "3_METERS_PER_SECOND": 2,
    3: "1_METERS_PER_SECOND", "1_METERS_PER_SECOND": 3,
    4: "0_3_METERS_PER_SECOND", "0_3_METERS_PER_SECOND": 4
}
MavOdidSpeedAcc = Literal[
    "UNKNOWN", "10_METERS_PER_SECOND", "3_METERS_PER_SECOND", "1_METERS_PER_SECOND", "0_3_METERS_PER_SECOND"]

MAV_ODID_TIME_ACC = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "0_1_SECOND", "0_1_SECOND": 1,
    2: "0_2_SECOND", "0_2_SECOND": 2,
    3: "0_3_SECOND", "0_3_SECOND": 3,
    4: "0_4_SECOND", "0_4_SECOND": 4,
    5: "0_5_SECOND", "0_5_SECOND": 5,
    6: "0_6_SECOND", "0_6_SECOND": 6,
    7: "0_7_SECOND", "0_7_SECOND": 7,
    8: "0_8_SECOND", "0_8_SECOND": 8,
    9: "0_9_SECOND", "0_9_SECOND": 9,
    10: "1_0_SECOND", "1_0_SECOND": 10,
    11: "1_1_SECOND", "1_1_SECOND": 11,
    12: "1_2_SECOND", "1_2_SECOND": 12,
    13: "1_3_SECOND", "1_3_SECOND": 13,
    14: "1_4_SECOND", "1_4_SECOND": 14,
    15: "1_5_SECOND", "1_5_SECOND": 15
}
MavOdidTimeAcc = Literal[
    "UNKNOWN", "0_1_SECOND", "0_2_SECOND", "0_3_SECOND", "0_4_SECOND", "0_5_SECOND", "0_6_SECOND", "0_7_SECOND", "0_8_SECOND", "0_9_SECOND", "1_0_SECOND", "1_1_SECOND", "1_2_SECOND", "1_3_SECOND", "1_4_SECOND", "1_5_SECOND"]

MAV_ODID_AUTH_TYPE = {
    0: "NONE", "NONE": 0,
    1: "UAS_ID_SIGNATURE", "UAS_ID_SIGNATURE": 1,
    2: "OPERATOR_ID_SIGNATURE", "OPERATOR_ID_SIGNATURE": 2,
    3: "MESSAGE_SET_SIGNATURE", "MESSAGE_SET_SIGNATURE": 3,
    4: "NETWORK_REMOTE_ID", "NETWORK_REMOTE_ID": 4,
    5: "SPECIFIC_AUTHENTICATION", "SPECIFIC_AUTHENTICATION": 5
}
MavOdidAuthType = Literal[
    "NONE", "UAS_ID_SIGNATURE", "OPERATOR_ID_SIGNATURE", "MESSAGE_SET_SIGNATURE", "NETWORK_REMOTE_ID", "SPECIFIC_AUTHENTICATION"]

MAV_ODID_DESC_TYPE = {
    0: "TEXT", "TEXT": 0,
    1: "EMERGENCY", "EMERGENCY": 1,
    2: "EXTENDED_STATUS", "EXTENDED_STATUS": 2
}
MavOdidDescType = Literal["TEXT", "EMERGENCY", "EXTENDED_STATUS"]

MAV_ODID_OPERATOR_LOCATION_TYPE = {
    0: "TAKEOFF", "TAKEOFF": 0,
    1: "LIVE_GNSS", "LIVE_GNSS": 1,
    2: "FIXED", "FIXED": 2
}
MavOdidOperatorLocationType = Literal["TAKEOFF", "LIVE_GNSS", "FIXED"]

MAV_ODID_CLASSIFICATION_TYPE = {
    0: "UNDECLARED", "UNDECLARED": 0,
    1: "EU", "EU": 1
}
MavOdidClassificationType = Literal["UNDECLARED", "EU"]

MAV_ODID_CATEGORY_EU = {
    0: "UNDECLARED", "UNDECLARED": 0,
    1: "OPEN", "OPEN": 1,
    2: "SPECIFIC", "SPECIFIC": 2,
    3: "CERTIFIED", "CERTIFIED": 3
}
MavOdidCategoryEu = Literal["UNDECLARED", "OPEN", "SPECIFIC", "CERTIFIED"]

MAV_ODID_CLASS_EU = {
    0: "UNDECLARED", "UNDECLARED": 0,
    1: "CLASS_0", "CLASS_0": 1,
    2: "CLASS_1", "CLASS_1": 2,
    3: "CLASS_2", "CLASS_2": 3,
    4: "CLASS_3", "CLASS_3": 4,
    5: "CLASS_4", "CLASS_4": 5,
    6: "CLASS_5", "CLASS_5": 6,
    7: "CLASS_6", "CLASS_6": 7
}
MavOdidClassEu = Literal["UNDECLARED", "CLASS_0", "CLASS_1", "CLASS_2", "CLASS_3", "CLASS_4", "CLASS_5", "CLASS_6"]

MAV_ODID_OPERATOR_ID_TYPE = {
    0: "CAA", "CAA": 0
}
MavOdidOperatorIdType = Literal["CAA"]

MAV_ODID_ARM_STATUS = {
    0: "GOOD_TO_ARM", "GOOD_TO_ARM": 0,
    1: "PRE_ARM_FAIL_GENERIC", "PRE_ARM_FAIL_GENERIC": 1
}
MavOdidArmStatus = Literal["GOOD_TO_ARM", "PRE_ARM_FAIL_GENERIC"]

TUNE_FORMAT = {
    1: "QBASIC1_1", "QBASIC1_1": 1,
    2: "MML_MODERN", "MML_MODERN": 2
}
TuneFormat = Literal["QBASIC1_1", "MML_MODERN"]

AIS_TYPE = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "RESERVED_1", "RESERVED_1": 1,
    2: "RESERVED_2", "RESERVED_2": 2,
    3: "RESERVED_3", "RESERVED_3": 3,
    4: "RESERVED_4", "RESERVED_4": 4,
    5: "RESERVED_5", "RESERVED_5": 5,
    6: "RESERVED_6", "RESERVED_6": 6,
    7: "RESERVED_7", "RESERVED_7": 7,
    8: "RESERVED_8", "RESERVED_8": 8,
    9: "RESERVED_9", "RESERVED_9": 9,
    10: "RESERVED_10", "RESERVED_10": 10,
    11: "RESERVED_11", "RESERVED_11": 11,
    12: "RESERVED_12", "RESERVED_12": 12,
    13: "RESERVED_13", "RESERVED_13": 13,
    14: "RESERVED_14", "RESERVED_14": 14,
    15: "RESERVED_15", "RESERVED_15": 15,
    16: "RESERVED_16", "RESERVED_16": 16,
    17: "RESERVED_17", "RESERVED_17": 17,
    18: "RESERVED_18", "RESERVED_18": 18,
    19: "RESERVED_19", "RESERVED_19": 19,
    20: "WIG", "WIG": 20,
    21: "WIG_HAZARDOUS_A", "WIG_HAZARDOUS_A": 21,
    22: "WIG_HAZARDOUS_B", "WIG_HAZARDOUS_B": 22,
    23: "WIG_HAZARDOUS_C", "WIG_HAZARDOUS_C": 23,
    24: "WIG_HAZARDOUS_D", "WIG_HAZARDOUS_D": 24,
    25: "WIG_RESERVED_1", "WIG_RESERVED_1": 25,
    26: "WIG_RESERVED_2", "WIG_RESERVED_2": 26,
    27: "WIG_RESERVED_3", "WIG_RESERVED_3": 27,
    28: "WIG_RESERVED_4", "WIG_RESERVED_4": 28,
    29: "WIG_RESERVED_5", "WIG_RESERVED_5": 29,
    30: "FISHING", "FISHING": 30,
    31: "TOWING", "TOWING": 31,
    32: "TOWING_LARGE", "TOWING_LARGE": 32,
    33: "DREDGING", "DREDGING": 33,
    34: "DIVING", "DIVING": 34,
    35: "MILITARY", "MILITARY": 35,
    36: "SAILING", "SAILING": 36,
    37: "PLEASURE", "PLEASURE": 37,
    38: "RESERVED_20", "RESERVED_20": 38,
    39: "RESERVED_21", "RESERVED_21": 39,
    40: "HSC", "HSC": 40,
    41: "HSC_HAZARDOUS_A", "HSC_HAZARDOUS_A": 41,
    42: "HSC_HAZARDOUS_B", "HSC_HAZARDOUS_B": 42,
    43: "HSC_HAZARDOUS_C", "HSC_HAZARDOUS_C": 43,
    44: "HSC_HAZARDOUS_D", "HSC_HAZARDOUS_D": 44,
    45: "HSC_RESERVED_1", "HSC_RESERVED_1": 45,
    46: "HSC_RESERVED_2", "HSC_RESERVED_2": 46,
    47: "HSC_RESERVED_3", "HSC_RESERVED_3": 47,
    48: "HSC_RESERVED_4", "HSC_RESERVED_4": 48,
    49: "HSC_UNKNOWN", "HSC_UNKNOWN": 49,
    50: "PILOT", "PILOT": 50,
    51: "SAR", "SAR": 51,
    52: "TUG", "TUG": 52,
    53: "PORT_TENDER", "PORT_TENDER": 53,
    54: "ANTI_POLLUTION", "ANTI_POLLUTION": 54,
    55: "LAW_ENFORCEMENT", "LAW_ENFORCEMENT": 55,
    56: "SPARE_LOCAL_1", "SPARE_LOCAL_1": 56,
    57: "SPARE_LOCAL_2", "SPARE_LOCAL_2": 57,
    58: "MEDICAL_TRANSPORT", "MEDICAL_TRANSPORT": 58,
    59: "NONECOMBATANT", "NONECOMBATANT": 59,
    60: "PASSENGER", "PASSENGER": 60,
    61: "PASSENGER_HAZARDOUS_A", "PASSENGER_HAZARDOUS_A": 61,
    62: "PASSENGER_HAZARDOUS_B", "PASSENGER_HAZARDOUS_B": 62,
    63: "PASSENGER_HAZARDOUS_C", "PASSENGER_HAZARDOUS_C": 63,
    64: "PASSENGER_HAZARDOUS_D", "PASSENGER_HAZARDOUS_D": 64,
    65: "PASSENGER_RESERVED_1", "PASSENGER_RESERVED_1": 65,
    66: "PASSENGER_RESERVED_2", "PASSENGER_RESERVED_2": 66,
    67: "PASSENGER_RESERVED_3", "PASSENGER_RESERVED_3": 67,
    68: "PASSENGER_RESERVED_4", "PASSENGER_RESERVED_4": 68,
    69: "PASSENGER_UNKNOWN", "PASSENGER_UNKNOWN": 69,
    70: "CARGO", "CARGO": 70,
    71: "CARGO_HAZARDOUS_A", "CARGO_HAZARDOUS_A": 71,
    72: "CARGO_HAZARDOUS_B", "CARGO_HAZARDOUS_B": 72,
    73: "CARGO_HAZARDOUS_C", "CARGO_HAZARDOUS_C": 73,
    74: "CARGO_HAZARDOUS_D", "CARGO_HAZARDOUS_D": 74,
    75: "CARGO_RESERVED_1", "CARGO_RESERVED_1": 75,
    76: "CARGO_RESERVED_2", "CARGO_RESERVED_2": 76,
    77: "CARGO_RESERVED_3", "CARGO_RESERVED_3": 77,
    78: "CARGO_RESERVED_4", "CARGO_RESERVED_4": 78,
    79: "CARGO_UNKNOWN", "CARGO_UNKNOWN": 79,
    80: "TANKER", "TANKER": 80,
    81: "TANKER_HAZARDOUS_A", "TANKER_HAZARDOUS_A": 81,
    82: "TANKER_HAZARDOUS_B", "TANKER_HAZARDOUS_B": 82,
    83: "TANKER_HAZARDOUS_C", "TANKER_HAZARDOUS_C": 83,
    84: "TANKER_HAZARDOUS_D", "TANKER_HAZARDOUS_D": 84,
    85: "TANKER_RESERVED_1", "TANKER_RESERVED_1": 85,
    86: "TANKER_RESERVED_2", "TANKER_RESERVED_2": 86,
    87: "TANKER_RESERVED_3", "TANKER_RESERVED_3": 87,
    88: "TANKER_RESERVED_4", "TANKER_RESERVED_4": 88,
    89: "TANKER_UNKNOWN", "TANKER_UNKNOWN": 89,
    90: "OTHER", "OTHER": 90,
    91: "OTHER_HAZARDOUS_A", "OTHER_HAZARDOUS_A": 91,
    92: "OTHER_HAZARDOUS_B", "OTHER_HAZARDOUS_B": 92,
    93: "OTHER_HAZARDOUS_C", "OTHER_HAZARDOUS_C": 93,
    94: "OTHER_HAZARDOUS_D", "OTHER_HAZARDOUS_D": 94,
    95: "OTHER_RESERVED_1", "OTHER_RESERVED_1": 95,
    96: "OTHER_RESERVED_2", "OTHER_RESERVED_2": 96,
    97: "OTHER_RESERVED_3", "OTHER_RESERVED_3": 97,
    98: "OTHER_RESERVED_4", "OTHER_RESERVED_4": 98,
    99: "OTHER_UNKNOWN", "OTHER_UNKNOWN": 99
}
AisType = Literal[
    "UNKNOWN", "RESERVED_1", "RESERVED_2", "RESERVED_3", "RESERVED_4", "RESERVED_5", "RESERVED_6", "RESERVED_7", "RESERVED_8", "RESERVED_9", "RESERVED_10", "RESERVED_11", "RESERVED_12", "RESERVED_13", "RESERVED_14", "RESERVED_15", "RESERVED_16", "RESERVED_17", "RESERVED_18", "RESERVED_19", "WIG", "WIG_HAZARDOUS_A", "WIG_HAZARDOUS_B", "WIG_HAZARDOUS_C", "WIG_HAZARDOUS_D", "WIG_RESERVED_1", "WIG_RESERVED_2", "WIG_RESERVED_3", "WIG_RESERVED_4", "WIG_RESERVED_5", "FISHING", "TOWING", "TOWING_LARGE", "DREDGING", "DIVING", "MILITARY", "SAILING", "PLEASURE", "RESERVED_20", "RESERVED_21", "HSC", "HSC_HAZARDOUS_A", "HSC_HAZARDOUS_B", "HSC_HAZARDOUS_C", "HSC_HAZARDOUS_D", "HSC_RESERVED_1", "HSC_RESERVED_2", "HSC_RESERVED_3", "HSC_RESERVED_4", "HSC_UNKNOWN", "PILOT", "SAR", "TUG", "PORT_TENDER", "ANTI_POLLUTION", "LAW_ENFORCEMENT", "SPARE_LOCAL_1", "SPARE_LOCAL_2", "MEDICAL_TRANSPORT", "NONECOMBATANT", "PASSENGER", "PASSENGER_HAZARDOUS_A", "PASSENGER_HAZARDOUS_B", "PASSENGER_HAZARDOUS_C", "PASSENGER_HAZARDOUS_D", "PASSENGER_RESERVED_1", "PASSENGER_RESERVED_2", "PASSENGER_RESERVED_3", "PASSENGER_RESERVED_4", "PASSENGER_UNKNOWN", "CARGO", "CARGO_HAZARDOUS_A", "CARGO_HAZARDOUS_B", "CARGO_HAZARDOUS_C", "CARGO_HAZARDOUS_D", "CARGO_RESERVED_1", "CARGO_RESERVED_2", "CARGO_RESERVED_3", "CARGO_RESERVED_4", "CARGO_UNKNOWN", "TANKER", "TANKER_HAZARDOUS_A", "TANKER_HAZARDOUS_B", "TANKER_HAZARDOUS_C", "TANKER_HAZARDOUS_D", "TANKER_RESERVED_1", "TANKER_RESERVED_2", "TANKER_RESERVED_3", "TANKER_RESERVED_4", "TANKER_UNKNOWN", "OTHER", "OTHER_HAZARDOUS_A", "OTHER_HAZARDOUS_B", "OTHER_HAZARDOUS_C", "OTHER_HAZARDOUS_D", "OTHER_RESERVED_1", "OTHER_RESERVED_2", "OTHER_RESERVED_3", "OTHER_RESERVED_4", "OTHER_UNKNOWN"]

AIS_NAV_STATUS = {
    0: "UNDER_WAY", "UNDER_WAY": 0,
    1: "ANCHORED", "ANCHORED": 1,
    2: "UN_COMMANDED", "UN_COMMANDED": 2,
    3: "RESTRICTED_MANOEUVERABILITY", "RESTRICTED_MANOEUVERABILITY": 3,
    4: "DRAUGHT_CONSTRAINED", "DRAUGHT_CONSTRAINED": 4,
    5: "MOORED", "MOORED": 5,
    6: "AGROUND", "AGROUND": 6,
    7: "FISHING", "FISHING": 7,
    8: "SAILING", "SAILING": 8,
    9: "RESERVED_HSC", "RESERVED_HSC": 9,
    10: "RESERVED_WIG", "RESERVED_WIG": 10,
    11: "RESERVED_1", "RESERVED_1": 11,
    12: "RESERVED_2", "RESERVED_2": 12,
    13: "RESERVED_3", "RESERVED_3": 13,
    14: "AIS_SART", "AIS_SART": 14,
    15: "UNKNOWN", "UNKNOWN": 15
}
AisNavStatus = Literal[
    "UNDER_WAY", "ANCHORED", "UN_COMMANDED", "RESTRICTED_MANOEUVERABILITY", "DRAUGHT_CONSTRAINED", "MOORED", "AGROUND", "FISHING", "SAILING", "RESERVED_HSC", "RESERVED_WIG", "RESERVED_1", "RESERVED_2", "RESERVED_3", "AIS_SART", "UNKNOWN"]

AIS_FLAGS = {
    1: "POSITION_ACCURACY", "POSITION_ACCURACY": 1,
    2: "VALID_COG", "VALID_COG": 2,
    4: "VALID_VELOCITY", "VALID_VELOCITY": 4,
    8: "HIGH_VELOCITY", "HIGH_VELOCITY": 8,
    16: "VALID_TURN_RATE", "VALID_TURN_RATE": 16,
    32: "TURN_RATE_SIGN_ONLY", "TURN_RATE_SIGN_ONLY": 32,
    64: "VALID_DIMENSIONS", "VALID_DIMENSIONS": 64,
    128: "LARGE_BOW_DIMENSION", "LARGE_BOW_DIMENSION": 128,
    256: "LARGE_STERN_DIMENSION", "LARGE_STERN_DIMENSION": 256,
    512: "LARGE_PORT_DIMENSION", "LARGE_PORT_DIMENSION": 512,
    1024: "LARGE_STARBOARD_DIMENSION", "LARGE_STARBOARD_DIMENSION": 1024,
    2048: "VALID_CALLSIGN", "VALID_CALLSIGN": 2048,
    4096: "VALID_NAME", "VALID_NAME": 4096
}
AisFlags = Literal[
    "POSITION_ACCURACY", "VALID_COG", "VALID_VELOCITY", "HIGH_VELOCITY", "VALID_TURN_RATE", "TURN_RATE_SIGN_ONLY", "VALID_DIMENSIONS", "LARGE_BOW_DIMENSION", "LARGE_STERN_DIMENSION", "LARGE_PORT_DIMENSION", "LARGE_STARBOARD_DIMENSION", "VALID_CALLSIGN", "VALID_NAME"]

FAILURE_UNIT = {
    0: "ENSOR_GYRO", "ENSOR_GYRO": 0,
    1: "ENSOR_ACCEL", "ENSOR_ACCEL": 1,
    2: "ENSOR_MAG", "ENSOR_MAG": 2,
    3: "ENSOR_BARO", "ENSOR_BARO": 3,
    4: "ENSOR_GPS", "ENSOR_GPS": 4,
    5: "ENSOR_OPTICAL_FLOW", "ENSOR_OPTICAL_FLOW": 5,
    6: "ENSOR_VIO", "ENSOR_VIO": 6,
    7: "ENSOR_DISTANCE_SENSOR", "ENSOR_DISTANCE_SENSOR": 7,
    8: "ENSOR_AIRSPEED", "ENSOR_AIRSPEED": 8,
    100: "YSTEM_BATTERY", "YSTEM_BATTERY": 100,
    101: "YSTEM_MOTOR", "YSTEM_MOTOR": 101,
    102: "YSTEM_SERVO", "YSTEM_SERVO": 102,
    103: "YSTEM_AVOIDANCE", "YSTEM_AVOIDANCE": 103,
    104: "YSTEM_RC_SIGNAL", "YSTEM_RC_SIGNAL": 104,
    105: "YSTEM_MAVLINK_SIGNAL", "YSTEM_MAVLINK_SIGNAL": 105
}
FailureUnit = Literal[
    "ENSOR_GYRO", "ENSOR_ACCEL", "ENSOR_MAG", "ENSOR_BARO", "ENSOR_GPS", "ENSOR_OPTICAL_FLOW", "ENSOR_VIO", "ENSOR_DISTANCE_SENSOR", "ENSOR_AIRSPEED", "YSTEM_BATTERY", "YSTEM_MOTOR", "YSTEM_SERVO", "YSTEM_AVOIDANCE", "YSTEM_RC_SIGNAL", "YSTEM_MAVLINK_SIGNAL"]

FAILURE_TYPE = {
    0: "OK", "OK": 0,
    1: "OFF", "OFF": 1,
    2: "STUCK", "STUCK": 2,
    3: "GARBAGE", "GARBAGE": 3,
    4: "WRONG", "WRONG": 4,
    5: "SLOW", "SLOW": 5,
    6: "DELAYED", "DELAYED": 6,
    7: "INTERMITTENT", "INTERMITTENT": 7
}
FailureType = Literal["OK", "OFF", "STUCK", "GARBAGE", "WRONG", "SLOW", "DELAYED", "INTERMITTENT"]

NAV_VTOL_LAND_OPTIONS = {
    0: "DEFAULT", "DEFAULT": 0,
    1: "FW_DESCENT", "FW_DESCENT": 1,
    2: "HOVER_DESCENT", "HOVER_DESCENT": 2
}
NavVtolLandOptions = Literal["DEFAULT", "FW_DESCENT", "HOVER_DESCENT"]

MAV_WINCH_STATUS_FLAG = {
    1: "HEALTHY", "HEALTHY": 1,
    2: "FULLY_RETRACTED", "FULLY_RETRACTED": 2,
    4: "MOVING", "MOVING": 4,
    8: "CLUTCH_ENGAGED", "CLUTCH_ENGAGED": 8,
    16: "LOCKED", "LOCKED": 16,
    32: "DROPPING", "DROPPING": 32,
    64: "ARRESTING", "ARRESTING": 64,
    128: "GROUND_SENSE", "GROUND_SENSE": 128,
    256: "RETRACTING", "RETRACTING": 256,
    512: "REDELIVER", "REDELIVER": 512,
    1024: "ABANDON_LINE", "ABANDON_LINE": 1024,
    2048: "LOCKING", "LOCKING": 2048,
    4096: "LOAD_LINE", "LOAD_LINE": 4096,
    8192: "LOAD_PAYLOAD", "LOAD_PAYLOAD": 8192
}
MavWinchStatusFlag = Literal[
    "HEALTHY", "FULLY_RETRACTED", "MOVING", "CLUTCH_ENGAGED", "LOCKED", "DROPPING", "ARRESTING", "GROUND_SENSE", "RETRACTING", "REDELIVER", "ABANDON_LINE", "LOCKING", "LOAD_LINE", "LOAD_PAYLOAD"]

MAG_CAL_STATUS = {
    0: "NOT_STARTED", "NOT_STARTED": 0,
    1: "WAITING_TO_START", "WAITING_TO_START": 1,
    2: "RUNNING_STEP_ONE", "RUNNING_STEP_ONE": 2,
    3: "RUNNING_STEP_TWO", "RUNNING_STEP_TWO": 3,
    4: "SUCCESS", "SUCCESS": 4,
    5: "FAILED", "FAILED": 5,
    6: "BAD_ORIENTATION", "BAD_ORIENTATION": 6,
    7: "BAD_RADIUS", "BAD_RADIUS": 7
}
MagCalStatus = Literal[
    "NOT_STARTED", "WAITING_TO_START", "RUNNING_STEP_ONE", "RUNNING_STEP_TWO", "SUCCESS", "FAILED", "BAD_ORIENTATION", "BAD_RADIUS"]

MAV_EVENT_ERROR_REASON = {
    0: "UNAVAILABLE", "UNAVAILABLE": 0
}
MavEventErrorReason = Literal["UNAVAILABLE"]

MAV_EVENT_CURRENT_SEQUENCE_FLAGS = {
    1: "RESET", "RESET": 1
}
MavEventCurrentSequenceFlags = Literal["RESET"]

HIL_SENSOR_UPDATED_FLAGS = {
    1: "XACC", "XACC": 1,
    2: "YACC", "YACC": 2,
    4: "ZACC", "ZACC": 4,
    8: "XGYRO", "XGYRO": 8,
    16: "YGYRO", "YGYRO": 16,
    32: "ZGYRO", "ZGYRO": 32,
    64: "XMAG", "XMAG": 64,
    128: "YMAG", "YMAG": 128,
    256: "ZMAG", "ZMAG": 256,
    512: "ABS_PRESSURE", "ABS_PRESSURE": 512,
    1024: "DIFF_PRESSURE", "DIFF_PRESSURE": 1024,
    2048: "PRESSURE_ALT", "PRESSURE_ALT": 2048,
    4096: "TEMPERATURE", "TEMPERATURE": 4096,
    2147483648: "RESET", "RESET": 2147483648
}
HilSensorUpdatedFlags = Literal[
    "XACC", "YACC", "ZACC", "XGYRO", "YGYRO", "ZGYRO", "XMAG", "YMAG", "ZMAG", "ABS_PRESSURE", "DIFF_PRESSURE", "PRESSURE_ALT", "TEMPERATURE", "RESET"]

HIGHRES_IMU_UPDATED_FLAGS = {
    1: "XACC", "XACC": 1,
    2: "YACC", "YACC": 2,
    4: "ZACC", "ZACC": 4,
    8: "XGYRO", "XGYRO": 8,
    16: "YGYRO", "YGYRO": 16,
    32: "ZGYRO", "ZGYRO": 32,
    64: "XMAG", "XMAG": 64,
    128: "YMAG", "YMAG": 128,
    256: "ZMAG", "ZMAG": 256,
    512: "ABS_PRESSURE", "ABS_PRESSURE": 512,
    1024: "DIFF_PRESSURE", "DIFF_PRESSURE": 1024,
    2048: "PRESSURE_ALT", "PRESSURE_ALT": 2048,
    4096: "TEMPERATURE", "TEMPERATURE": 4096
}
HighresImuUpdatedFlags = Literal[
    "XACC", "YACC", "ZACC", "XGYRO", "YGYRO", "ZGYRO", "XMAG", "YMAG", "ZMAG", "ABS_PRESSURE", "DIFF_PRESSURE", "PRESSURE_ALT", "TEMPERATURE"]

CAN_FILTER_OP = {
    0: "REPLACE", "REPLACE": 0,
    1: "ADD", "ADD": 1,
    2: "REMOVE", "REMOVE": 2
}
CanFilterOp = Literal["REPLACE", "ADD", "REMOVE"]

MAV_FTP_ERR = {
    0: "NONE", "NONE": 0,
    1: "FAIL", "FAIL": 1,
    2: "FAILERRNO", "FAILERRNO": 2,
    3: "INVALIDDATASIZE", "INVALIDDATASIZE": 3,
    4: "INVALIDSESSION", "INVALIDSESSION": 4,
    5: "NOSESSIONSAVAILABLE", "NOSESSIONSAVAILABLE": 5,
    6: "EOF", "EOF": 6,
    7: "UNKNOWNCOMMAND", "UNKNOWNCOMMAND": 7,
    8: "FILEEXISTS", "FILEEXISTS": 8,
    9: "FILEPROTECTED", "FILEPROTECTED": 9,
    10: "FILENOTFOUND", "FILENOTFOUND": 10
}
MavFtpErr = Literal[
    "NONE", "FAIL", "FAILERRNO", "INVALIDDATASIZE", "INVALIDSESSION", "NOSESSIONSAVAILABLE", "EOF", "UNKNOWNCOMMAND", "FILEEXISTS", "FILEPROTECTED", "FILENOTFOUND"]

MAV_FTP_OPCODE = {
    0: "NONE", "NONE": 0,
    1: "TERMINATESESSION", "TERMINATESESSION": 1,
    2: "RESETSESSION", "RESETSESSION": 2,
    3: "LISTDIRECTORY", "LISTDIRECTORY": 3,
    4: "OPENFILERO", "OPENFILERO": 4,
    5: "READFILE", "READFILE": 5,
    6: "CREATEFILE", "CREATEFILE": 6,
    7: "WRITEFILE", "WRITEFILE": 7,
    8: "REMOVEFILE", "REMOVEFILE": 8,
    9: "CREATEDIRECTORY", "CREATEDIRECTORY": 9,
    10: "REMOVEDIRECTORY", "REMOVEDIRECTORY": 10,
    11: "OPENFILEWO", "OPENFILEWO": 11,
    12: "TRUNCATEFILE", "TRUNCATEFILE": 12,
    13: "RENAME", "RENAME": 13,
    14: "CALCFILECRC", "CALCFILECRC": 14,
    15: "BURSTREADFILE", "BURSTREADFILE": 15,
    128: "ACK", "ACK": 128,
    129: "NAK", "NAK": 129
}
MavFtpOpcode = Literal[
    "NONE", "TERMINATESESSION", "RESETSESSION", "LISTDIRECTORY", "OPENFILERO", "READFILE", "CREATEFILE", "WRITEFILE", "REMOVEFILE", "CREATEDIRECTORY", "REMOVEDIRECTORY", "OPENFILEWO", "TRUNCATEFILE", "RENAME", "CALCFILECRC", "BURSTREADFILE", "ACK", "NAK"]

MISSION_STATE = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "NO_MISSION", "NO_MISSION": 1,
    2: "NOT_STARTED", "NOT_STARTED": 2,
    3: "ACTIVE", "ACTIVE": 3,
    4: "PAUSED", "PAUSED": 4,
    5: "COMPLETE", "COMPLETE": 5
}
MissionState = Literal["UNKNOWN", "NO_MISSION", "NOT_STARTED", "ACTIVE", "PAUSED", "COMPLETE"]

SAFETY_SWITCH_STATE = {
    0: "SAFE", "SAFE": 0,
    1: "DANGEROUS", "DANGEROUS": 1
}
SafetySwitchState = Literal["SAFE", "DANGEROUS"]

ILLUMINATOR_MODE = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "INTERNAL_CONTROL", "INTERNAL_CONTROL": 1,
    2: "EXTERNAL_SYNC", "EXTERNAL_SYNC": 2
}
IlluminatorMode = Literal["UNKNOWN", "INTERNAL_CONTROL", "EXTERNAL_SYNC"]

ILLUMINATOR_ERROR_FLAGS = {
    1: "THERMAL_THROTTLING", "THERMAL_THROTTLING": 1,
    2: "OVER_TEMPERATURE_SHUTDOWN", "OVER_TEMPERATURE_SHUTDOWN": 2,
    4: "THERMISTOR_FAILURE", "THERMISTOR_FAILURE": 4
}
IlluminatorErrorFlags = Literal["THERMAL_THROTTLING", "OVER_TEMPERATURE_SHUTDOWN", "THERMISTOR_FAILURE"]

MAV_STANDARD_MODE = {
    0: "NON_STANDARD", "NON_STANDARD": 0,
    1: "POSITION_HOLD", "POSITION_HOLD": 1,
    2: "ORBIT", "ORBIT": 2,
    3: "CRUISE", "CRUISE": 3,
    4: "ALTITUDE_HOLD", "ALTITUDE_HOLD": 4,
    5: "SAFE_RECOVERY", "SAFE_RECOVERY": 5,
    6: "MISSION", "MISSION": 6,
    7: "LAND", "LAND": 7,
    8: "TAKEOFF", "TAKEOFF": 8
}
MavStandardMode = Literal[
    "NON_STANDARD", "POSITION_HOLD", "ORBIT", "CRUISE", "ALTITUDE_HOLD", "SAFE_RECOVERY", "MISSION", "LAND", "TAKEOFF"]

MAV_MODE_PROPERTY = {
    1: "ADVANCED", "ADVANCED": 1,
    2: "NOT_USER_SELECTABLE", "NOT_USER_SELECTABLE": 2,
    4: "AUTO_MODE", "AUTO_MODE": 4
}
MavModeProperty = Literal["ADVANCED", "NOT_USER_SELECTABLE", "AUTO_MODE"]

HIL_ACTUATOR_CONTROLS_FLAGS = {
    1: "LOCKSTEP", "LOCKSTEP": 1
}
HilActuatorControlsFlags = Literal["LOCKSTEP"]

MAV_BOOL = {
    0: "FALSE", "FALSE": 0,
    1: "TRUE", "TRUE": 1
}
MavBool = Literal["FALSE", "TRUE"]

MAV_PROTOCOL_CAPABILITY = {
    1: "MISSION_FLOAT", "MISSION_FLOAT": 1,
    2: "PARAM_FLOAT", "PARAM_FLOAT": 2,
    4: "MISSION_INT", "MISSION_INT": 4,
    8: "COMMAND_INT", "COMMAND_INT": 8,
    16: "PARAM_ENCODE_BYTEWISE", "PARAM_ENCODE_BYTEWISE": 16,
    32: "FTP", "FTP": 32,
    64: "SET_ATTITUDE_TARGET", "SET_ATTITUDE_TARGET": 64,
    128: "SET_POSITION_TARGET_LOCAL_NED", "SET_POSITION_TARGET_LOCAL_NED": 128,
    256: "SET_POSITION_TARGET_GLOBAL_INT", "SET_POSITION_TARGET_GLOBAL_INT": 256,
    512: "TERRAIN", "TERRAIN": 512,
    1024: "RESERVED3", "RESERVED3": 1024,
    2048: "FLIGHT_TERMINATION", "FLIGHT_TERMINATION": 2048,
    4096: "COMPASS_CALIBRATION", "COMPASS_CALIBRATION": 4096,
    8192: "MAVLINK2", "MAVLINK2": 8192,
    16384: "MISSION_FENCE", "MISSION_FENCE": 16384,
    32768: "MISSION_RALLY", "MISSION_RALLY": 32768,
    65536: "RESERVED2", "RESERVED2": 65536,
    131072: "PARAM_ENCODE_C_CAST", "PARAM_ENCODE_C_CAST": 131072,
    262144: "COMPONENT_IMPLEMENTS_GIMBAL_MANAGER", "COMPONENT_IMPLEMENTS_GIMBAL_MANAGER": 262144,
    524288: "COMPONENT_ACCEPTS_GCS_CONTROL", "COMPONENT_ACCEPTS_GCS_CONTROL": 524288,
    1048576: "GRIPPER", "GRIPPER": 1048576
}
MavProtocolCapability = Literal[
    "MISSION_FLOAT", "PARAM_FLOAT", "MISSION_INT", "COMMAND_INT", "PARAM_ENCODE_BYTEWISE", "FTP", "SET_ATTITUDE_TARGET", "SET_POSITION_TARGET_LOCAL_NED", "SET_POSITION_TARGET_GLOBAL_INT", "TERRAIN", "RESERVED3", "FLIGHT_TERMINATION", "COMPASS_CALIBRATION", "MAVLINK2", "MISSION_FENCE", "MISSION_RALLY", "RESERVED2", "PARAM_ENCODE_C_CAST", "COMPONENT_IMPLEMENTS_GIMBAL_MANAGER", "COMPONENT_ACCEPTS_GCS_CONTROL", "GRIPPER"]

FIRMWARE_VERSION_TYPE = {
    0: "DEV", "DEV": 0,
    64: "ALPHA", "ALPHA": 64,
    128: "BETA", "BETA": 128,
    192: "RC", "RC": 192,
    255: "OFFICIAL", "OFFICIAL": 255
}
FirmwareVersionType = Literal["DEV", "ALPHA", "BETA", "RC", "OFFICIAL"]

MAV_AUTOPILOT = {
    0: "GENERIC", "GENERIC": 0,
    1: "RESERVED", "RESERVED": 1,
    2: "SLUGS", "SLUGS": 2,
    3: "ARDUPILOTMEGA", "ARDUPILOTMEGA": 3,
    4: "OPENPILOT", "OPENPILOT": 4,
    5: "GENERIC_WAYPOINTS_ONLY", "GENERIC_WAYPOINTS_ONLY": 5,
    6: "GENERIC_WAYPOINTS_AND_SIMPLE_NAVIGATION_ONLY", "GENERIC_WAYPOINTS_AND_SIMPLE_NAVIGATION_ONLY": 6,
    7: "GENERIC_MISSION_FULL", "GENERIC_MISSION_FULL": 7,
    8: "INVALID", "INVALID": 8,
    9: "PPZ", "PPZ": 9,
    10: "UDB", "UDB": 10,
    11: "FP", "FP": 11,
    12: "PX4", "PX4": 12,
    13: "SMACCMPILOT", "SMACCMPILOT": 13,
    14: "AUTOQUAD", "AUTOQUAD": 14,
    15: "ARMAZILA", "ARMAZILA": 15,
    16: "AEROB", "AEROB": 16,
    17: "ASLUAV", "ASLUAV": 17,
    18: "SMARTAP", "SMARTAP": 18,
    19: "AIRRAILS", "AIRRAILS": 19,
    20: "REFLEX", "REFLEX": 20
}
MavAutopilot = Literal[
    "GENERIC", "RESERVED", "SLUGS", "ARDUPILOTMEGA", "OPENPILOT", "GENERIC_WAYPOINTS_ONLY", "GENERIC_WAYPOINTS_AND_SIMPLE_NAVIGATION_ONLY", "GENERIC_MISSION_FULL", "INVALID", "PPZ", "UDB", "FP", "PX4", "SMACCMPILOT", "AUTOQUAD", "ARMAZILA", "AEROB", "ASLUAV", "SMARTAP", "AIRRAILS", "REFLEX"]

MAV_TYPE = {
    0: "GENERIC", "GENERIC": 0,
    1: "FIXED_WING", "FIXED_WING": 1,
    2: "QUADROTOR", "QUADROTOR": 2,
    3: "COAXIAL", "COAXIAL": 3,
    4: "HELICOPTER", "HELICOPTER": 4,
    5: "ANTENNA_TRACKER", "ANTENNA_TRACKER": 5,
    6: "GCS", "GCS": 6,
    7: "AIRSHIP", "AIRSHIP": 7,
    8: "FREE_BALLOON", "FREE_BALLOON": 8,
    9: "ROCKET", "ROCKET": 9,
    10: "GROUND_ROVER", "GROUND_ROVER": 10,
    11: "SURFACE_BOAT", "SURFACE_BOAT": 11,
    12: "SUBMARINE", "SUBMARINE": 12,
    13: "HEXAROTOR", "HEXAROTOR": 13,
    14: "OCTOROTOR", "OCTOROTOR": 14,
    15: "TRICOPTER", "TRICOPTER": 15,
    16: "FLAPPING_WING", "FLAPPING_WING": 16,
    17: "KITE", "KITE": 17,
    18: "ONBOARD_CONTROLLER", "ONBOARD_CONTROLLER": 18,
    19: "VTOL_TAILSITTER_DUOROTOR", "VTOL_TAILSITTER_DUOROTOR": 19,
    20: "VTOL_TAILSITTER_QUADROTOR", "VTOL_TAILSITTER_QUADROTOR": 20,
    21: "VTOL_TILTROTOR", "VTOL_TILTROTOR": 21,
    22: "VTOL_FIXEDROTOR", "VTOL_FIXEDROTOR": 22,
    23: "VTOL_TAILSITTER", "VTOL_TAILSITTER": 23,
    24: "VTOL_TILTWING", "VTOL_TILTWING": 24,
    25: "VTOL_RESERVED5", "VTOL_RESERVED5": 25,
    26: "GIMBAL", "GIMBAL": 26,
    27: "ADSB", "ADSB": 27,
    28: "PARAFOIL", "PARAFOIL": 28,
    29: "DODECAROTOR", "DODECAROTOR": 29,
    30: "CAMERA", "CAMERA": 30,
    31: "CHARGING_STATION", "CHARGING_STATION": 31,
    32: "FLARM", "FLARM": 32,
    33: "SERVO", "SERVO": 33,
    34: "ODID", "ODID": 34,
    35: "DECAROTOR", "DECAROTOR": 35,
    36: "BATTERY", "BATTERY": 36,
    37: "PARACHUTE", "PARACHUTE": 37,
    38: "LOG", "LOG": 38,
    39: "OSD", "OSD": 39,
    40: "IMU", "IMU": 40,
    41: "GPS", "GPS": 41,
    42: "WINCH", "WINCH": 42,
    43: "GENERIC_MULTIROTOR", "GENERIC_MULTIROTOR": 43,
    44: "ILLUMINATOR", "ILLUMINATOR": 44,
    45: "SPACECRAFT_ORBITER", "SPACECRAFT_ORBITER": 45,
    46: "GROUND_QUADRUPED", "GROUND_QUADRUPED": 46,
    47: "VTOL_GYRODYNE", "VTOL_GYRODYNE": 47,
    48: "GRIPPER", "GRIPPER": 48,
    49: "RADIO", "RADIO": 49
}
MavType = Literal[
    "GENERIC", "FIXED_WING", "QUADROTOR", "COAXIAL", "HELICOPTER", "ANTENNA_TRACKER", "GCS", "AIRSHIP", "FREE_BALLOON", "ROCKET", "GROUND_ROVER", "SURFACE_BOAT", "SUBMARINE", "HEXAROTOR", "OCTOROTOR", "TRICOPTER", "FLAPPING_WING", "KITE", "ONBOARD_CONTROLLER", "VTOL_TAILSITTER_DUOROTOR", "VTOL_TAILSITTER_QUADROTOR", "VTOL_TILTROTOR", "VTOL_FIXEDROTOR", "VTOL_TAILSITTER", "VTOL_TILTWING", "VTOL_RESERVED5", "GIMBAL", "ADSB", "PARAFOIL", "DODECAROTOR", "CAMERA", "CHARGING_STATION", "FLARM", "SERVO", "ODID", "DECAROTOR", "BATTERY", "PARACHUTE", "LOG", "OSD", "IMU", "GPS", "WINCH", "GENERIC_MULTIROTOR", "ILLUMINATOR", "SPACECRAFT_ORBITER", "GROUND_QUADRUPED", "VTOL_GYRODYNE", "GRIPPER", "RADIO"]

MAV_MODE_FLAG = {
    1: "CUSTOM_MODE_ENABLED", "CUSTOM_MODE_ENABLED": 1,
    2: "TEST_ENABLED", "TEST_ENABLED": 2,
    4: "AUTO_ENABLED", "AUTO_ENABLED": 4,
    8: "GUIDED_ENABLED", "GUIDED_ENABLED": 8,
    16: "STABILIZE_ENABLED", "STABILIZE_ENABLED": 16,
    32: "HIL_ENABLED", "HIL_ENABLED": 32,
    64: "MANUAL_INPUT_ENABLED", "MANUAL_INPUT_ENABLED": 64,
    128: "SAFETY_ARMED", "SAFETY_ARMED": 128
}
MavModeFlag = Literal[
    "CUSTOM_MODE_ENABLED", "TEST_ENABLED", "AUTO_ENABLED", "GUIDED_ENABLED", "STABILIZE_ENABLED", "HIL_ENABLED", "MANUAL_INPUT_ENABLED", "SAFETY_ARMED"]

MAV_MODE_FLAG_DECODE_POSITION = {
    1: "CUSTOM_MODE", "CUSTOM_MODE": 1,
    2: "TEST", "TEST": 2,
    4: "AUTO", "AUTO": 4,
    8: "GUIDED", "GUIDED": 8,
    16: "STABILIZE", "STABILIZE": 16,
    32: "HIL", "HIL": 32,
    64: "MANUAL", "MANUAL": 64,
    128: "SAFETY", "SAFETY": 128
}
MavModeFlagDecodePosition = Literal["CUSTOM_MODE", "TEST", "AUTO", "GUIDED", "STABILIZE", "HIL", "MANUAL", "SAFETY"]

MAV_STATE = {
    0: "UNINIT", "UNINIT": 0,
    1: "BOOT", "BOOT": 1,
    2: "CALIBRATING", "CALIBRATING": 2,
    3: "STANDBY", "STANDBY": 3,
    4: "ACTIVE", "ACTIVE": 4,
    5: "CRITICAL", "CRITICAL": 5,
    6: "EMERGENCY", "EMERGENCY": 6,
    7: "POWEROFF", "POWEROFF": 7,
    8: "FLIGHT_TERMINATION", "FLIGHT_TERMINATION": 8
}
MavState = Literal[
    "UNINIT", "BOOT", "CALIBRATING", "STANDBY", "ACTIVE", "CRITICAL", "EMERGENCY", "POWEROFF", "FLIGHT_TERMINATION"]

MAV_COMPONENT = {
    0: "ALL", "ALL": 0,
    1: "AUTOPILOT1", "AUTOPILOT1": 1,
    25: "USER1", "USER1": 25,
    26: "USER2", "USER2": 26,
    27: "USER3", "USER3": 27,
    28: "USER4", "USER4": 28,
    29: "USER5", "USER5": 29,
    30: "USER6", "USER6": 30,
    31: "USER7", "USER7": 31,
    32: "USER8", "USER8": 32,
    33: "USER9", "USER9": 33,
    34: "USER10", "USER10": 34,
    35: "USER11", "USER11": 35,
    36: "USER12", "USER12": 36,
    37: "USER13", "USER13": 37,
    38: "USER14", "USER14": 38,
    39: "USER15", "USER15": 39,
    40: "USER16", "USER16": 40,
    41: "USER17", "USER17": 41,
    42: "USER18", "USER18": 42,
    43: "USER19", "USER19": 43,
    44: "USER20", "USER20": 44,
    45: "USER21", "USER21": 45,
    46: "USER22", "USER22": 46,
    47: "USER23", "USER23": 47,
    48: "USER24", "USER24": 48,
    49: "USER25", "USER25": 49,
    50: "USER26", "USER26": 50,
    51: "USER27", "USER27": 51,
    52: "USER28", "USER28": 52,
    53: "USER29", "USER29": 53,
    54: "USER30", "USER30": 54,
    55: "USER31", "USER31": 55,
    56: "USER32", "USER32": 56,
    57: "USER33", "USER33": 57,
    58: "USER34", "USER34": 58,
    59: "USER35", "USER35": 59,
    60: "USER36", "USER36": 60,
    61: "USER37", "USER37": 61,
    62: "USER38", "USER38": 62,
    63: "USER39", "USER39": 63,
    64: "USER40", "USER40": 64,
    65: "USER41", "USER41": 65,
    66: "USER42", "USER42": 66,
    67: "USER43", "USER43": 67,
    68: "TELEMETRY_RADIO", "TELEMETRY_RADIO": 68,
    69: "USER45", "USER45": 69,
    70: "USER46", "USER46": 70,
    71: "USER47", "USER47": 71,
    72: "USER48", "USER48": 72,
    73: "USER49", "USER49": 73,
    74: "USER50", "USER50": 74,
    75: "USER51", "USER51": 75,
    76: "USER52", "USER52": 76,
    77: "USER53", "USER53": 77,
    78: "USER54", "USER54": 78,
    79: "USER55", "USER55": 79,
    80: "USER56", "USER56": 80,
    81: "USER57", "USER57": 81,
    82: "USER58", "USER58": 82,
    83: "USER59", "USER59": 83,
    84: "USER60", "USER60": 84,
    85: "USER61", "USER61": 85,
    86: "USER62", "USER62": 86,
    87: "USER63", "USER63": 87,
    88: "USER64", "USER64": 88,
    89: "USER65", "USER65": 89,
    90: "USER66", "USER66": 90,
    91: "USER67", "USER67": 91,
    92: "USER68", "USER68": 92,
    93: "USER69", "USER69": 93,
    94: "USER70", "USER70": 94,
    95: "USER71", "USER71": 95,
    96: "USER72", "USER72": 96,
    97: "USER73", "USER73": 97,
    98: "USER74", "USER74": 98,
    99: "USER75", "USER75": 99,
    100: "CAMERA", "CAMERA": 100,
    101: "CAMERA2", "CAMERA2": 101,
    102: "CAMERA3", "CAMERA3": 102,
    103: "CAMERA4", "CAMERA4": 103,
    104: "CAMERA5", "CAMERA5": 104,
    105: "CAMERA6", "CAMERA6": 105,
    110: "RADIO", "RADIO": 110,
    111: "RADIO2", "RADIO2": 111,
    112: "RADIO3", "RADIO3": 112,
    140: "SERVO1", "SERVO1": 140,
    141: "SERVO2", "SERVO2": 141,
    142: "SERVO3", "SERVO3": 142,
    143: "SERVO4", "SERVO4": 143,
    144: "SERVO5", "SERVO5": 144,
    145: "SERVO6", "SERVO6": 145,
    146: "SERVO7", "SERVO7": 146,
    147: "SERVO8", "SERVO8": 147,
    148: "SERVO9", "SERVO9": 148,
    149: "SERVO10", "SERVO10": 149,
    150: "SERVO11", "SERVO11": 150,
    151: "SERVO12", "SERVO12": 151,
    152: "SERVO13", "SERVO13": 152,
    153: "SERVO14", "SERVO14": 153,
    154: "GIMBAL", "GIMBAL": 154,
    155: "LOG", "LOG": 155,
    156: "ADSB", "ADSB": 156,
    157: "OSD", "OSD": 157,
    158: "PERIPHERAL", "PERIPHERAL": 158,
    159: "QX1_GIMBAL", "QX1_GIMBAL": 159,
    160: "FLARM", "FLARM": 160,
    161: "PARACHUTE", "PARACHUTE": 161,
    169: "WINCH", "WINCH": 169,
    171: "GIMBAL2", "GIMBAL2": 171,
    172: "GIMBAL3", "GIMBAL3": 172,
    173: "GIMBAL4", "GIMBAL4": 173,
    174: "GIMBAL5", "GIMBAL5": 174,
    175: "GIMBAL6", "GIMBAL6": 175,
    180: "BATTERY", "BATTERY": 180,
    181: "BATTERY2", "BATTERY2": 181,
    189: "MAVCAN", "MAVCAN": 189,
    190: "MISSIONPLANNER", "MISSIONPLANNER": 190,
    191: "ONBOARD_COMPUTER", "ONBOARD_COMPUTER": 191,
    192: "ONBOARD_COMPUTER2", "ONBOARD_COMPUTER2": 192,
    193: "ONBOARD_COMPUTER3", "ONBOARD_COMPUTER3": 193,
    194: "ONBOARD_COMPUTER4", "ONBOARD_COMPUTER4": 194,
    195: "PATHPLANNER", "PATHPLANNER": 195,
    196: "OBSTACLE_AVOIDANCE", "OBSTACLE_AVOIDANCE": 196,
    197: "VISUAL_INERTIAL_ODOMETRY", "VISUAL_INERTIAL_ODOMETRY": 197,
    198: "PAIRING_MANAGER", "PAIRING_MANAGER": 198,
    200: "IMU", "IMU": 200,
    201: "IMU_2", "IMU_2": 201,
    202: "IMU_3", "IMU_3": 202,
    220: "GPS", "GPS": 220,
    221: "GPS2", "GPS2": 221,
    236: "ODID_TXRX_1", "ODID_TXRX_1": 236,
    237: "ODID_TXRX_2", "ODID_TXRX_2": 237,
    238: "ODID_TXRX_3", "ODID_TXRX_3": 238,
    240: "UDP_BRIDGE", "UDP_BRIDGE": 240,
    241: "UART_BRIDGE", "UART_BRIDGE": 241,
    242: "TUNNEL_NODE", "TUNNEL_NODE": 242,
    243: "ILLUMINATOR", "ILLUMINATOR": 243,
    250: "SYSTEM_CONTROL", "SYSTEM_CONTROL": 250
}
MavComponent = Literal[
    "ALL", "AUTOPILOT1", "USER1", "USER2", "USER3", "USER4", "USER5", "USER6", "USER7", "USER8", "USER9", "USER10", "USER11", "USER12", "USER13", "USER14", "USER15", "USER16", "USER17", "USER18", "USER19", "USER20", "USER21", "USER22", "USER23", "USER24", "USER25", "USER26", "USER27", "USER28", "USER29", "USER30", "USER31", "USER32", "USER33", "USER34", "USER35", "USER36", "USER37", "USER38", "USER39", "USER40", "USER41", "USER42", "USER43", "TELEMETRY_RADIO", "USER45", "USER46", "USER47", "USER48", "USER49", "USER50", "USER51", "USER52", "USER53", "USER54", "USER55", "USER56", "USER57", "USER58", "USER59", "USER60", "USER61", "USER62", "USER63", "USER64", "USER65", "USER66", "USER67", "USER68", "USER69", "USER70", "USER71", "USER72", "USER73", "USER74", "USER75", "CAMERA", "CAMERA2", "CAMERA3", "CAMERA4", "CAMERA5", "CAMERA6", "RADIO", "RADIO2", "RADIO3", "SERVO1", "SERVO2", "SERVO3", "SERVO4", "SERVO5", "SERVO6", "SERVO7", "SERVO8", "SERVO9", "SERVO10", "SERVO11", "SERVO12", "SERVO13", "SERVO14", "GIMBAL", "LOG", "ADSB", "OSD", "PERIPHERAL", "QX1_GIMBAL", "FLARM", "PARACHUTE", "WINCH", "GIMBAL2", "GIMBAL3", "GIMBAL4", "GIMBAL5", "GIMBAL6", "BATTERY", "BATTERY2", "MAVCAN", "MISSIONPLANNER", "ONBOARD_COMPUTER", "ONBOARD_COMPUTER2", "ONBOARD_COMPUTER3", "ONBOARD_COMPUTER4", "PATHPLANNER", "OBSTACLE_AVOIDANCE", "VISUAL_INERTIAL_ODOMETRY", "PAIRING_MANAGER", "IMU", "IMU_2", "IMU_3", "GPS", "GPS2", "ODID_TXRX_1", "ODID_TXRX_2", "ODID_TXRX_3", "UDP_BRIDGE", "UART_BRIDGE", "TUNNEL_NODE", "ILLUMINATOR", "SYSTEM_CONTROL"]
