from typing import Literal

AIRSPEED_SENSOR_FLAGS = {
    1: "NHEALTHY", "NHEALTHY": 1,
    2: "SING", "SING": 2
}
AirspeedSensorFlags = Literal["NHEALTHY", "SING"]

MAV_BATTERY_STATUS_FLAGS = {
    1: "NOT_READY_TO_USE", "NOT_READY_TO_USE": 1,
    2: "CHARGING", "CHARGING": 2,
    4: "CELL_BALANCING", "CELL_BALANCING": 4,
    8: "FAULT_CELL_IMBALANCE", "FAULT_CELL_IMBALANCE": 8,
    16: "AUTO_DISCHARGING", "AUTO_DISCHARGING": 16,
    32: "REQUIRES_SERVICE", "REQUIRES_SERVICE": 32,
    64: "BAD_BATTERY", "BAD_BATTERY": 64,
    128: "PROTECTIONS_ENABLED", "PROTECTIONS_ENABLED": 128,
    256: "FAULT_PROTECTION_SYSTEM", "FAULT_PROTECTION_SYSTEM": 256,
    512: "FAULT_OVER_VOLT", "FAULT_OVER_VOLT": 512,
    1024: "FAULT_UNDER_VOLT", "FAULT_UNDER_VOLT": 1024,
    2048: "FAULT_OVER_TEMPERATURE", "FAULT_OVER_TEMPERATURE": 2048,
    4096: "FAULT_UNDER_TEMPERATURE", "FAULT_UNDER_TEMPERATURE": 4096,
    8192: "FAULT_OVER_CURRENT", "FAULT_OVER_CURRENT": 8192,
    16384: "FAULT_SHORT_CIRCUIT", "FAULT_SHORT_CIRCUIT": 16384,
    32768: "FAULT_INCOMPATIBLE_VOLTAGE", "FAULT_INCOMPATIBLE_VOLTAGE": 32768,
    65536: "FAULT_INCOMPATIBLE_FIRMWARE", "FAULT_INCOMPATIBLE_FIRMWARE": 65536,
    131072: "FAULT_INCOMPATIBLE_CELLS_CONFIGURATION", "FAULT_INCOMPATIBLE_CELLS_CONFIGURATION": 131072,
    262144: "CAPACITY_RELATIVE_TO_FULL", "CAPACITY_RELATIVE_TO_FULL": 262144,
    2147483648: "EXTENDED", "EXTENDED": 2147483648
}
MavBatteryStatusFlags = Literal[
    "NOT_READY_TO_USE", "CHARGING", "CELL_BALANCING", "FAULT_CELL_IMBALANCE", "AUTO_DISCHARGING", "REQUIRES_SERVICE", "BAD_BATTERY", "PROTECTIONS_ENABLED", "FAULT_PROTECTION_SYSTEM", "FAULT_OVER_VOLT", "FAULT_UNDER_VOLT", "FAULT_OVER_TEMPERATURE", "FAULT_UNDER_TEMPERATURE", "FAULT_OVER_CURRENT", "FAULT_SHORT_CIRCUIT", "FAULT_INCOMPATIBLE_VOLTAGE", "FAULT_INCOMPATIBLE_FIRMWARE", "FAULT_INCOMPATIBLE_CELLS_CONFIGURATION", "CAPACITY_RELATIVE_TO_FULL", "EXTENDED"]

GCS_CONTROL_STATUS_FLAGS = {
    1: "SYSTEM_MANAGER", "SYSTEM_MANAGER": 1,
    2: "TAKEOVER_ALLOWED", "TAKEOVER_ALLOWED": 2
}
GcsControlStatusFlags = Literal["SYSTEM_MANAGER", "TAKEOVER_ALLOWED"]

TARGET_ABSOLUTE_SENSOR_CAPABILITY_FLAGS = {
    1: "POSITION", "POSITION": 1,
    2: "VELOCITY", "VELOCITY": 2,
    4: "ACCELERATION", "ACCELERATION": 4,
    8: "ATTITUDE", "ATTITUDE": 8,
    16: "RATES", "RATES": 16
}
TargetAbsoluteSensorCapabilityFlags = Literal["POSITION", "VELOCITY", "ACCELERATION", "ATTITUDE", "RATES"]

TARGET_OBS_FRAME = {
    0: "LOCAL_NED", "LOCAL_NED": 0,
    1: "BODY_FRD", "BODY_FRD": 1,
    2: "LOCAL_OFFSET_NED", "LOCAL_OFFSET_NED": 2,
    3: "OTHER", "OTHER": 3
}
TargetObsFrame = Literal["LOCAL_NED", "BODY_FRD", "LOCAL_OFFSET_NED", "OTHER"]

RADIO_RC_CHANNELS_FLAGS = {
    1: "FAILSAFE", "FAILSAFE": 1,
    2: "OUTDATED", "OUTDATED": 2
}
RadioRcChannelsFlags = Literal["FAILSAFE", "OUTDATED"]

GPS_SYSTEM_ERROR_FLAGS = {
    1: "INCOMING_CORRECTIONS", "INCOMING_CORRECTIONS": 1,
    2: "CONFIGURATION", "CONFIGURATION": 2,
    4: "SOFTWARE", "SOFTWARE": 4,
    8: "ANTENNA", "ANTENNA": 8,
    16: "EVENT_CONGESTION", "EVENT_CONGESTION": 16,
    32: "CPU_OVERLOAD", "CPU_OVERLOAD": 32,
    64: "OUTPUT_CONGESTION", "OUTPUT_CONGESTION": 64
}
GpsSystemErrorFlags = Literal[
    "INCOMING_CORRECTIONS", "CONFIGURATION", "SOFTWARE", "ANTENNA", "EVENT_CONGESTION", "CPU_OVERLOAD", "OUTPUT_CONGESTION"]

GPS_AUTHENTICATION_STATE = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "INITIALIZING", "INITIALIZING": 1,
    2: "ERROR", "ERROR": 2,
    3: "OK", "OK": 3,
    4: "DISABLED", "DISABLED": 4
}
GpsAuthenticationState = Literal["UNKNOWN", "INITIALIZING", "ERROR", "OK", "DISABLED"]

GPS_JAMMING_STATE = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "OK", "OK": 1,
    2: "MITIGATED", "MITIGATED": 2,
    3: "DETECTED", "DETECTED": 3
}
GpsJammingState = Literal["UNKNOWN", "OK", "MITIGATED", "DETECTED"]

GPS_SPOOFING_STATE = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "OK", "OK": 1,
    2: "MITIGATED", "MITIGATED": 2,
    3: "DETECTED", "DETECTED": 3
}
GpsSpoofingState = Literal["UNKNOWN", "OK", "MITIGATED", "DETECTED"]

GPS_RAIM_STATE = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "DISABLED", "DISABLED": 1,
    2: "OK", "OK": 2,
    3: "FAILED", "FAILED": 3
}
GpsRaimState = Literal["UNKNOWN", "DISABLED", "OK", "FAILED"]

ACTUATOR_TEST_GROUP = {
    0: "ROLL_TORQUE", "ROLL_TORQUE": 0,
    1: "PITCH_TORQUE", "PITCH_TORQUE": 1,
    2: "YAW_TORQUE", "YAW_TORQUE": 2,
    3: "COLLECTIVE_TILT", "COLLECTIVE_TILT": 3
}
ActuatorTestGroup = Literal["ROLL_TORQUE", "PITCH_TORQUE", "YAW_TORQUE", "COLLECTIVE_TILT"]

GLOBAL_POSITION_SRC = {
    0: "UNKNOWN", "UNKNOWN": 0,
    1: "GNSS", "GNSS": 1,
    2: "VISION", "VISION": 2,
    3: "PSEUDOLITES", "PSEUDOLITES": 3,
    4: "TRN", "TRN": 4,
    5: "MAGNETIC", "MAGNETIC": 5,
    6: "ESTIMATOR", "ESTIMATOR": 6
}
GlobalPositionSrc = Literal["UNKNOWN", "GNSS", "VISION", "PSEUDOLITES", "TRN", "MAGNETIC", "ESTIMATOR"]

GLOBAL_POSITION_FLAGS = {
    1: "UNHEALTHY", "UNHEALTHY": 1,
    2: "PRIMARY", "PRIMARY": 2
}
GlobalPositionFlags = Literal["UNHEALTHY", "PRIMARY"]
