from typing import Literal

MAV_PREFLIGHT_STORAGE_ACTION = {
    0: "READ_ALL", "READ_ALL": 0,
    1: "WRITE_ALL", "WRITE_ALL": 1,
    2: "CLEAR_ALL", "CLEAR_ALL": 2,
    3: "READ_SPECIFIC", "READ_SPECIFIC": 3,
    4: "WRITE_SPECIFIC", "WRITE_SPECIFIC": 4,
    5: "CLEAR_SPECIFIC", "CLEAR_SPECIFIC": 5,
    6: "DO_NOTHING", "DO_NOTHING": 6
}
MavPreflightStorageAction = Literal[
    "READ_ALL", "WRITE_ALL", "CLEAR_ALL", "READ_SPECIFIC", "WRITE_SPECIFIC", "CLEAR_SPECIFIC", "DO_NOTHING"]
