from typing import Literal

MAV_BOOL = {
    0: "FALSE", "FALSE": 0,
    1: "TRUE", "TRUE": 1
}
MavBool = Literal["FALSE", "TRUE"]

MAV_PROTOCOL_CAPABILITY = {
    1: "MISSION_FLOAT", "MISSION_FLOAT": 1,
    2: "PARAM_FLOAT", "PARAM_FLOAT": 2,
    4: "MISSION_INT", "MISSION_INT": 4,
    8: "COMMAND_INT", "COMMAND_INT": 8,
    16: "PARAM_ENCODE_BYTEWISE", "PARAM_ENCODE_BYTEWISE": 16,
    32: "FTP", "FTP": 32,
    64: "SET_ATTITUDE_TARGET", "SET_ATTITUDE_TARGET": 64,
    128: "SET_POSITION_TARGET_LOCAL_NED", "SET_POSITION_TARGET_LOCAL_NED": 128,
    256: "SET_POSITION_TARGET_GLOBAL_INT", "SET_POSITION_TARGET_GLOBAL_INT": 256,
    512: "TERRAIN", "TERRAIN": 512,
    1024: "RESERVED3", "RESERVED3": 1024,
    2048: "FLIGHT_TERMINATION", "FLIGHT_TERMINATION": 2048,
    4096: "COMPASS_CALIBRATION", "COMPASS_CALIBRATION": 4096,
    8192: "MAVLINK2", "MAVLINK2": 8192,
    16384: "MISSION_FENCE", "MISSION_FENCE": 16384,
    32768: "MISSION_RALLY", "MISSION_RALLY": 32768,
    65536: "RESERVED2", "RESERVED2": 65536,
    131072: "PARAM_ENCODE_C_CAST", "PARAM_ENCODE_C_CAST": 131072,
    262144: "COMPONENT_IMPLEMENTS_GIMBAL_MANAGER", "COMPONENT_IMPLEMENTS_GIMBAL_MANAGER": 262144,
    524288: "COMPONENT_ACCEPTS_GCS_CONTROL", "COMPONENT_ACCEPTS_GCS_CONTROL": 524288,
    1048576: "GRIPPER", "GRIPPER": 1048576
}
MavProtocolCapability = Literal[
    "MISSION_FLOAT", "PARAM_FLOAT", "MISSION_INT", "COMMAND_INT", "PARAM_ENCODE_BYTEWISE", "FTP", "SET_ATTITUDE_TARGET", "SET_POSITION_TARGET_LOCAL_NED", "SET_POSITION_TARGET_GLOBAL_INT", "TERRAIN", "RESERVED3", "FLIGHT_TERMINATION", "COMPASS_CALIBRATION", "MAVLINK2", "MISSION_FENCE", "MISSION_RALLY", "RESERVED2", "PARAM_ENCODE_C_CAST", "COMPONENT_IMPLEMENTS_GIMBAL_MANAGER", "COMPONENT_ACCEPTS_GCS_CONTROL", "GRIPPER"]

FIRMWARE_VERSION_TYPE = {
    0: "DEV", "DEV": 0,
    64: "ALPHA", "ALPHA": 64,
    128: "BETA", "BETA": 128,
    192: "RC", "RC": 192,
    255: "OFFICIAL", "OFFICIAL": 255
}
FirmwareVersionType = Literal["DEV", "ALPHA", "BETA", "RC", "OFFICIAL"]
