from typing import Literal

MAV_STORM32_TUNNEL_PAYLOAD_TYPE = {
    200: "1_IN", "1_IN": 200,
    201: "1_OUT", "1_OUT": 201,
    202: "2_IN", "2_IN": 202,
    203: "2_OUT", "2_OUT": 203,
    204: "3_IN", "3_IN": 204,
    205: "3_OUT", "3_OUT": 205
}
MavStorm32TunnelPayloadType = Literal["1_IN", "1_OUT", "2_IN", "2_OUT", "3_IN", "3_OUT"]

MAV_STORM32_GIMBAL_MANAGER_CAP_FLAGS = {
    1: "HAS_PROFILES", "HAS_PROFILES": 1
}
MavStorm32GimbalManagerCapFlags = Literal["HAS_PROFILES"]

MAV_STORM32_GIMBAL_MANAGER_FLAGS = {
    1: "RC_ACTIVE", "RC_ACTIVE": 1,
    2: "CLIENT_ONBOARD_ACTIVE", "CLIENT_ONBOARD_ACTIVE": 2,
    4: "CLIENT_AUTOPILOT_ACTIVE", "CLIENT_AUTOPILOT_ACTIVE": 4,
    8: "CLIENT_GCS_ACTIVE", "CLIENT_GCS_ACTIVE": 8,
    16: "CLIENT_CAMERA_ACTIVE", "CLIENT_CAMERA_ACTIVE": 16,
    32: "CLIENT_GCS2_ACTIVE", "CLIENT_GCS2_ACTIVE": 32,
    64: "CLIENT_CAMERA2_ACTIVE", "CLIENT_CAMERA2_ACTIVE": 64,
    128: "CLIENT_CUSTOM_ACTIVE", "CLIENT_CUSTOM_ACTIVE": 128,
    256: "CLIENT_CUSTOM2_ACTIVE", "CLIENT_CUSTOM2_ACTIVE": 256,
    512: "SET_SUPERVISON", "SET_SUPERVISON": 512,
    1024: "SET_RELEASE", "SET_RELEASE": 1024
}
MavStorm32GimbalManagerFlags = Literal[
    "RC_ACTIVE", "CLIENT_ONBOARD_ACTIVE", "CLIENT_AUTOPILOT_ACTIVE", "CLIENT_GCS_ACTIVE", "CLIENT_CAMERA_ACTIVE", "CLIENT_GCS2_ACTIVE", "CLIENT_CAMERA2_ACTIVE", "CLIENT_CUSTOM_ACTIVE", "CLIENT_CUSTOM2_ACTIVE", "SET_SUPERVISON", "SET_RELEASE"]

MAV_STORM32_GIMBAL_MANAGER_CLIENT = {
    0: "NONE", "NONE": 0,
    1: "ONBOARD", "ONBOARD": 1,
    2: "AUTOPILOT", "AUTOPILOT": 2,
    3: "GCS", "GCS": 3,
    4: "CAMERA", "CAMERA": 4,
    5: "GCS2", "GCS2": 5,
    6: "CAMERA2", "CAMERA2": 6,
    7: "CUSTOM", "CUSTOM": 7,
    8: "CUSTOM2", "CUSTOM2": 8
}
MavStorm32GimbalManagerClient = Literal[
    "NONE", "ONBOARD", "AUTOPILOT", "GCS", "CAMERA", "GCS2", "CAMERA2", "CUSTOM", "CUSTOM2"]

MAV_STORM32_GIMBAL_MANAGER_PROFILE = {
    0: "DEFAULT", "DEFAULT": 0,
    1: "CUSTOM", "CUSTOM": 1,
    2: "COOPERATIVE", "COOPERATIVE": 2,
    3: "EXCLUSIVE", "EXCLUSIVE": 3,
    4: "PRIORITY_COOPERATIVE", "PRIORITY_COOPERATIVE": 4,
    5: "PRIORITY_EXCLUSIVE", "PRIORITY_EXCLUSIVE": 5
}
MavStorm32GimbalManagerProfile = Literal[
    "DEFAULT", "CUSTOM", "COOPERATIVE", "EXCLUSIVE", "PRIORITY_COOPERATIVE", "PRIORITY_EXCLUSIVE"]

MAV_QSHOT_MODE = {
    0: "UNDEFINED", "UNDEFINED": 0,
    1: "DEFAULT", "DEFAULT": 1,
    2: "GIMBAL_RETRACT", "GIMBAL_RETRACT": 2,
    3: "GIMBAL_NEUTRAL", "GIMBAL_NEUTRAL": 3,
    4: "GIMBAL_MISSION", "GIMBAL_MISSION": 4,
    5: "GIMBAL_RC_CONTROL", "GIMBAL_RC_CONTROL": 5,
    6: "POI_TARGETING", "POI_TARGETING": 6,
    7: "SYSID_TARGETING", "SYSID_TARGETING": 7,
    8: "CABLECAM_2POINT", "CABLECAM_2POINT": 8,
    9: "HOME_TARGETING", "HOME_TARGETING": 9
}
MavQshotMode = Literal[
    "UNDEFINED", "DEFAULT", "GIMBAL_RETRACT", "GIMBAL_NEUTRAL", "GIMBAL_MISSION", "GIMBAL_RC_CONTROL", "POI_TARGETING", "SYSID_TARGETING", "CABLECAM_2POINT", "HOME_TARGETING"]

MLRS_RADIO_LINK_STATS_FLAGS = {
    1: "RSSI_DBM", "RSSI_DBM": 1,
    2: "RX_RECEIVE_ANTENNA2", "RX_RECEIVE_ANTENNA2": 2,
    4: "RX_TRANSMIT_ANTENNA1", "RX_TRANSMIT_ANTENNA1": 4,
    8: "RX_TRANSMIT_ANTENNA2", "RX_TRANSMIT_ANTENNA2": 8,
    16: "TX_RECEIVE_ANTENNA2", "TX_RECEIVE_ANTENNA2": 16,
    32: "TX_TRANSMIT_ANTENNA1", "TX_TRANSMIT_ANTENNA1": 32,
    64: "TX_TRANSMIT_ANTENNA2", "TX_TRANSMIT_ANTENNA2": 64
}
MlrsRadioLinkStatsFlags = Literal[
    "RSSI_DBM", "RX_RECEIVE_ANTENNA2", "RX_TRANSMIT_ANTENNA1", "RX_TRANSMIT_ANTENNA2", "TX_RECEIVE_ANTENNA2", "TX_TRANSMIT_ANTENNA1", "TX_TRANSMIT_ANTENNA2"]

MLRS_RADIO_LINK_TYPE = {
    0: "GENERIC", "GENERIC": 0,
    1: "HERELINK", "HERELINK": 1,
    2: "DRAGONLINK", "DRAGONLINK": 2,
    3: "RFD900", "RFD900": 3,
    4: "CROSSFIRE", "CROSSFIRE": 4,
    5: "EXPRESSLRS", "EXPRESSLRS": 5,
    6: "MLRS", "MLRS": 6
}
MlrsRadioLinkType = Literal["GENERIC", "HERELINK", "DRAGONLINK", "RFD900", "CROSSFIRE", "EXPRESSLRS", "MLRS"]
